Repository Rayman-Sodhi/Clone-IT, pull requests merged in 2022-04, with the labels that each got.

#229 Auto assign issue
  .github/workflows/Auto_message_on_issue_open.yml
  .github/workflows/auto_assign.yml
  .github/workflows/issue-labeler.yml
  2048/.gitignore
  2048/package-lock.json
  2048/package.json
  2048/public/2048.svg
  2048/public/index.html
  2048/public/manifest.json
  2048/public/robots.txt
  2048/src/Styles.js
  2048/src/TwentyFourtyEight.css
  2048/src/TwentyFourtyEight.js
  2048/src/grid.svg
  2048/src/index.css
  2048/src/index.js
  2048/src/package.json
  2048/src/restart.svg
  2048/src/serviceWorker.js
  2048/src/undo.svg
  assets/Khsuhbu Resume.png
  assets/Resume with bootstrap.pdf
  assets/Resume without boostrap.pdf
Labels: Level1, GSSoC22

#225 2048 game
  2048/.gitignore
  2048/package-lock.json
  2048/package.json
  2048/public/2048.svg
  2048/public/index.html
  2048/public/manifest.json
  2048/public/robots.txt
  2048/src/Styles.js
  2048/src/TwentyFourtyEight.css
  2048/src/TwentyFourtyEight.js
  2048/src/grid.svg
  2048/src/index.css
  2048/src/index.js
  2048/src/package.json
  2048/src/restart.svg
  2048/src/serviceWorker.js
  2048/src/undo.svg
  assets/Khsuhbu Resume.png
  assets/Resume with bootstrap.pdf
  assets/Resume without boostrap.pdf
Labels: GSSoC22

#233 Clones linked
  2048 Clone/.gitignore
  2048 Clone/package-lock.json
  2048 Clone/package.json
  2048 Clone/public/2048.svg
  2048 Clone/public/index.html
  2048 Clone/public/manifest.json
  2048 Clone/public/robots.txt
  2048 Clone/src/Styles.js
  2048 Clone/src/TwentyFourtyEight.css
  2048 Clone/src/TwentyFourtyEight.js
  2048 Clone/src/grid.svg
  2048 Clone/src/index.css
  2048 Clone/src/index.js
  2048 Clone/src/package.json
  2048 Clone/src/restart.svg
  2048 Clone/src/serviceWorker.js
  2048 Clone/src/undo.svg
  INDEX-JS/clones.js
  README.md
  assets/2048.png
  assets/microsoft-teams.svg
  assets/pluralsight.png
  assets/unsplash.png
  assets/whatsapp.svg
  assets/windows11.png
  assets/zomato.svg
  index.css
  index.html
Labels: Level1, GSSoC22

#235 kali-org-homepage-clone
  Kali homepage/.gitignore
  Kali homepage/README.md
  Kali homepage/package-lock.json
  Kali homepage/package.json
  Kali homepage/public/favicon.ico
  Kali homepage/public/index.html
  Kali homepage/public/manifest.json
  Kali homepage/public/robots.txt
  Kali homepage/src/App.js
  Kali homepage/src/components/Container-1/container-1.css
  Kali homepage/src/components/Container-1/index.js
  Kali homepage/src/components/Container-2/container-2.css
  Kali homepage/src/components/Container-2/index.js
  Kali homepage/src/components/Header/Header.css
  Kali homepage/src/components/Header/index.js
  Kali homepage/src/index.css
  Kali homepage/src/index.js
  Kali homepage/src/pages/index.js
  Kali homepage/src/reportWebVitals.js
Labels: GSSoC22

#238 Grammarly(Character Counter)
  Grammarly(Character Counter)/index.html
  Grammarly(Character Counter)/readme.md
  Grammarly(Character Counter)/script.js
  Grammarly(Character Counter)/style.css
Labels: GSSoC22, Level3

#241 Chabot created
  chatwoot.js
  index.css
  index.html
Labels: GSSoC22, Level3

#245 Avengers Puzzle Game Clone
  Avengers Puzzle Game/images/1.jpg
  Avengers Puzzle Game/images/10.jpg
  Avengers Puzzle Game/images/11.jpg
  Avengers Puzzle Game/images/12.jpg
  Avengers Puzzle Game/images/13.jpg
  Avengers Puzzle Game/images/14.jpg
  Avengers Puzzle Game/images/15.jpg
  Avengers Puzzle Game/images/16.jpg
  Avengers Puzzle Game/images/17.jpg
  Avengers Puzzle Game/images/18.jpg
  Avengers Puzzle Game/images/19.jpg
  Avengers Puzzle Game/images/2.jpg
  Avengers Puzzle Game/images/20.jpg
  Avengers Puzzle Game/images/21.jpg
  Avengers Puzzle Game/images/22.jpg
  Avengers Puzzle Game/images/23.jpg
  Avengers Puzzle Game/images/24.jpg
  Avengers Puzzle Game/images/25.jpg
  Avengers Puzzle Game/images/26.jpg
  Avengers Puzzle Game/images/3.jpg
  Avengers Puzzle Game/images/4.jpg
  Avengers Puzzle Game/images/5.jpg
  Avengers Puzzle Game/images/6.jpg
  Avengers Puzzle Game/images/7.jpg
  Avengers Puzzle Game/images/8.jpg
  Avengers Puzzle Game/images/9.jpg
  Avengers Puzzle Game/images/blank.jpg
  Avengers Puzzle Game/images/blank2.jpg
  Avengers Puzzle Game/index.html
  Avengers Puzzle Game/readme.md
  Avengers Puzzle Game/script.js
  Avengers Puzzle Game/style.css
Labels: GSSoC22

#246 Better Styling
  Discord_App_Clone/assets/css/style.css
  Discord_App_Clone/home.html
Labels: GSSoC22

#253 Footer Icons hover
  Amazone Clone/.gitignore
  Amazone Clone/functions/.eslintrc.json
  Amazone Clone/functions/.gitignore
  Amazone Clone/functions/index.js
  Amazone Clone/functions/package-lock.json
  Amazone Clone/functions/package.json
  Amazone Clone/functions/ui-debug.log
  Amazone Clone/package-lock.json
  Amazone Clone/package.json
  Amazone Clone/public/favicon.ico
  Amazone Clone/public/index.html
  Amazone Clone/public/logo192.png
  Amazone Clone/public/logo512.png
  Amazone Clone/public/manifest.json
  Amazone Clone/public/robots.txt
  Amazone Clone/src/App.css
  Amazone Clone/src/App.js
  Amazone Clone/src/App.test.js
  Amazone Clone/src/Checkout.css
  Amazone Clone/src/Checkout.js
  Amazone Clone/src/CheckoutProduct.css
  Amazone Clone/src/CheckoutProduct.js
  Amazone Clone/src/Header.css
  Amazone Clone/src/Header.js
  Amazone Clone/src/Home.css
  Amazone Clone/src/Home.js
  Amazone Clone/src/Login.css
  Amazone Clone/src/Login.js
  Amazone Clone/src/Order.css
  Amazone Clone/src/Order.js
  Amazone Clone/src/Orders.css
  Amazone Clone/src/Orders.js
  Amazone Clone/src/Payment.css
  Amazone Clone/src/Payment.js
  Amazone Clone/src/Product.css
  Amazone Clone/src/Product.js
  Amazone Clone/src/StateProvider.js
  Amazone Clone/src/Subtotal.css
  Amazone Clone/src/Subtotal.js
  Amazone Clone/src/axios.js
  Amazone Clone/src/firebase.js
  Amazone Clone/src/index.css
  Amazone Clone/src/index.js
  Amazone Clone/src/reducer.js
  Amazone Clone/src/reportWebVitals.js
  Amazone Clone/src/serviceWorker.js
  Amazone Clone/src/setupTests.js
  index.css
  index.html
Labels: GSSoC22

#254 Adding the hamburger toggle button in navbar
  index.css
  index.html
Labels: GSSoC22

#263 Scroll button placement
  index.css
  index.html
Labels: Level1, GSSoC22, fixed

#251 Added a button to scroll to the top
  index.css
  index.html
Labels: GSSoC22

#264 Update scroll top btn
  index.css
Labels: Level1, GSSoC22

#266 Update README.md
  README.md
Labels: Level1, GSSoC22

#269 Dino Games Clone
  Dino Games Clone/cactus.png
  Dino Games Clone/cactus2.png
  Dino Games Clone/dinobackground.png
  Dino Games Clone/dinosaur.png
  Dino Games Clone/index.html
  Dino Games Clone/main.js
  Dino Games Clone/readme.md
  Dino Games Clone/style.css
Labels: GSSoC22

#260 Myntra Clone using React Js
  Myntra Clone/.gitignore
  Myntra Clone/README.md
  Myntra Clone/package-lock.json
  Myntra Clone/package.json
  Myntra Clone/public/favicon.ico
  Myntra Clone/public/index.html
  Myntra Clone/public/manifest.json
  Myntra Clone/src/App.css
  Myntra Clone/src/App.js
  Myntra Clone/src/App.test.js
  Myntra Clone/src/components/BrandFocusCard/BrandFocusCard.js
  Myntra Clone/src/components/BrandInFocusViewPort/BrandInFocusViewPort.css
  Myntra Clone/src/components/BrandInFocusViewPort/BrandInFocusViewPort.js
  Myntra Clone/src/components/Containers/LayoutContainer/Layout.css
  Myntra Clone/src/components/Containers/LayoutContainer/Layout.js
  Myntra Clone/src/components/Crousel/Crousel.css
  Myntra Clone/src/components/Crousel/Crousel.js
  Myntra Clone/src/components/DealCard/DealCard.css
  Myntra Clone/src/components/DealCard/DealCard.js
  Myntra Clone/src/components/DealCardViewPort/DealCardViewPort.css
  Myntra Clone/src/components/DealCardViewPort/DealCardViewPort.js
  Myntra Clone/src/components/Header/Header.css
  Myntra Clone/src/components/Header/Header.js
  Myntra Clone/src/components/Header/styled/BrandLogo.js
  Myntra Clone/src/components/Header/styled/HeaderStyle.js
  Myntra Clone/src/components/Header/styled/NavLink.js
  Myntra Clone/src/components/Header/styled/PictureLink.js
  Myntra Clone/src/components/Header/styled/SearchBar.js
  Myntra Clone/src/data.js
  Myntra Clone/src/index.css
  Myntra Clone/src/index.js
  Myntra Clone/src/myntraSprite.png
  Myntra Clone/src/serviceWorker.js
  Myntra Clone/yarn.lock
Labels: GSSoC22

#270 Extra footer removed
  index.html
Labels: GSSoC22

#279 Coin Toss Clone
  Coin Toss Clone/heads.svg
  Coin Toss Clone/index.html
  Coin Toss Clone/readme.md
  Coin Toss Clone/script.js
  Coin Toss Clone/style.css
  Coin Toss Clone/tails.svg
Labels: GSSoC22

#282 Fix typos and grammar mistakes in README.md
  README.md
Labels: documentation

#273 Add a Twitter-Homepage Clone
  Twitter-Clone/.gitignore
  Twitter-Clone/README.md
  Twitter-Clone/package-lock.json
  Twitter-Clone/package.json
  Twitter-Clone/public/favicon.ico
  Twitter-Clone/public/icons8-twitter-48.png
  Twitter-Clone/public/index.html
  Twitter-Clone/public/logo192.png
  Twitter-Clone/public/logo512.png
  Twitter-Clone/public/manifest.json
  Twitter-Clone/public/robots.txt
  Twitter-Clone/src/App.css
  Twitter-Clone/src/App.js
  Twitter-Clone/src/Feed.css
  Twitter-Clone/src/Feed.js
  Twitter-Clone/src/Post.css
  Twitter-Clone/src/Post.js
  Twitter-Clone/src/Sidebar.css
  Twitter-Clone/src/Sidebar.js
  Twitter-Clone/src/SidebarOption.css
  Twitter-Clone/src/SidebarOption.js
  Twitter-Clone/src/TweetBox.css
  Twitter-Clone/src/TweetBox.js
  Twitter-Clone/src/Widgets.css
  Twitter-Clone/src/Widgets.js
  Twitter-Clone/src/index.css
  Twitter-Clone/src/index.js
  Twitter-Clone/src/logo.svg
  Twitter-Clone/src/reportWebVitals.js
  Twitter-Clone/src/setupTests.js
Labels: enhancement

#286 Uber Eats Clone
  Uber Eats Clone/Assets/Gregs.png
  Uber Eats Clone/Assets/beef-burger.jpg
  Uber Eats Clone/Assets/burger.png
  Uber Eats Clone/Assets/card_payment_icons_stripe_mobile.png
  Uber Eats Clone/Assets/coca-cola-2.jpg.crdownload
  Uber Eats Clone/Assets/coca-cola-2.png
  Uber Eats Clone/Assets/coca-cola.jpg
  Uber Eats Clone/Assets/coca-cola.jpg.crdownload
  Uber Eats Clone/Assets/cupcake.png
  Uber Eats Clone/Assets/deals.png
  Uber Eats Clone/Assets/doughnuts.png
  Uber Eats Clone/Assets/drink.png
  Uber Eats Clone/Assets/dummy__pic.jpg
  Uber Eats Clone/Assets/empty cart.svg
  Uber Eats Clone/Assets/fish.png
  Uber Eats Clone/Assets/food.jpg
  Uber Eats Clone/Assets/fried-chickedn.jpg
  Uber Eats Clone/Assets/fruits.png
  Uber Eats Clone/Assets/grilled-kebab.jpg
  Uber Eats Clone/Assets/healthy-food.png
  Uber Eats Clone/Assets/japanese-food.png
  Uber Eats Clone/Assets/juice-jar.jpg
  Uber Eats Clone/Assets/koushari.jpg
  Uber Eats Clone/Assets/lobster.jpg
  Uber Eats Clone/Assets/man-avatar.png
  Uber Eats Clone/Assets/markus-winkler-b_xYQe69eec-unsplash.jpg
  Uber Eats Clone/Assets/olena-sergienko-YhMZRcdjARQ-unsplash.jpg
  Uber Eats Clone/Assets/pizza.jpg
  Uber Eats Clone/Assets/pizza.png
  Uber Eats Clone/Assets/rasberry_pop.jpg
  Uber Eats Clone/Assets/salad.png
  Uber Eats Clone/Assets/soda.jpg
  Uber Eats Clone/Assets/spmb.jpg
  Uber Eats Clone/Assets/sushi maki.jpg
  Uber Eats Clone/Assets/tester.png
  Uber Eats Clone/Assets/tteok.png
  Uber Eats Clone/Assets/turkey.jpg
  Uber Eats Clone/Assets/uberEatsLogo.png
  Uber Eats Clone/Assets/water.jpg
  Uber Eats Clone/Fonts/UberMoveBold.otf
  Uber Eats Clone/Fonts/UberMoveMedium.otf
  Uber Eats Clone/index.html
  Uber Eats Clone/readme.md
  Uber Eats Clone/script.js
  Uber Eats Clone/style.css
Labels: Level2, GSSoC22

#290 Login page FACEBOOK CLONE
  FACEBOOK-CLONE/fb clone/app.css
  FACEBOOK-CLONE/fb clone/index.html
Labels: GSSoC22

#272 Add a Codepen Clone
  Codepen-Clone/.gitignore
  Codepen-Clone/README.md
  Codepen-Clone/package-lock.json
  Codepen-Clone/package.json
  Codepen-Clone/public/codepenlogo.png
  Codepen-Clone/public/favicon.ico
  Codepen-Clone/public/index.html
  Codepen-Clone/public/manifest.json
  Codepen-Clone/public/robots.txt
  Codepen-Clone/src/components/App.js
  Codepen-Clone/src/components/Editor.js
  Codepen-Clone/src/hooks/useLocalStorage.js
  Codepen-Clone/src/index.css
  Codepen-Clone/src/index.js
Labels: GSSoC22, Level3

#292 Connectivity done with the LOGIN page for the FACEBOOK Clone
  FACEBOOK-CLONE/app.css
  FACEBOOK-CLONE/login.html
Labels: GSSoC22

#298 Added changes to the navbar items
  index.css
Labels: Level1, GSSoC22

#296 Instagram Clone Added
  Instagram_Clone/assets/images/crop.png
  Instagram_Clone/assets/images/logo.png
  Instagram_Clone/assets/images/post-1.jpg
  Instagram_Clone/assets/images/post-2.jpg
  Instagram_Clone/assets/images/post-3.jpg
  Instagram_Clone/assets/images/search.png
  Instagram_Clone/assets/images/story.png
  Instagram_Clone/assets/images/user-1.jpg
  Instagram_Clone/assets/images/user-2.jpeg
  Instagram_Clone/assets/images/user-3.jpeg
  Instagram_Clone/assets/images/user-4.jpeg
  Instagram_Clone/assets/images/user-5.jpeg
  Instagram_Clone/index.html
  Instagram_Clone/style.css
Labels: Level2, GSSoC22

#303 Wordle-Clone
  Wordle_Clone/index.html
  Wordle_Clone/script.js
  Wordle_Clone/style.css
Labels: GSSoC22

#299 Fixed hamburger issues
  index.css
  index.html
Labels: GSSoC22

#305 Added JS for hamburger
  index.html
Labels: GSSoC22

#306 tripadvisor clone
  .vs/Clone-IT/v17/.suo
  .vs/slnx.sqlite
  README.md
  TRIPADVISOR/img/ghi.jpg
  TRIPADVISOR/img/logo.svg
  TRIPADVISOR/index.html
  TRIPADVISOR/style.css
Labels: Level2, GSSoC22

#314 pinterest
  .DS_Store
  pinterest/index.html
  pinterest/logo.png
  pinterest/style.css
  pinterest/vu.png
Labels: Level2, GSSoC22

#310 Added LinkedIn Clone
  LinkedIn_Clone/favicon.png
  LinkedIn_Clone/icons8-linkedin-48.svg
  LinkedIn_Clone/index.html
  LinkedIn_Clone/style.css
Labels: GSSoC22

#315 Instagram Login Page clone from scratch
  Instagram Login Page/facebook.png
  Instagram Login Page/index.html
  Instagram Login Page/instagram.png
  Instagram Login Page/styles.css
  Instagram_Clone/login-assets/app-store.png
  Instagram_Clone/login-assets/google-play.png
  Instagram_Clone/login-assets/logo.png
  Instagram_Clone/login-assets/mobile-app.png
  Instagram_Clone/login.css
  Instagram_Clone/login.html
Labels: GSSoC22

#322 Wikipedia HomePage Clone:
  Wikipedia HomePage Clone/W.png
  Wikipedia HomePage Clone/app-store.png
  Wikipedia HomePage Clone/commons.svg
  Wikipedia HomePage Clone/index.html
  Wikipedia HomePage Clone/mediawiki.png
  Wikipedia HomePage Clone/meta-wiki.png
  Wikipedia HomePage Clone/play-store.png
  Wikipedia HomePage Clone/readme.md
  Wikipedia HomePage Clone/style.css
  Wikipedia HomePage Clone/wikibooks.png
  Wikipedia HomePage Clone/wikidata.png
  Wikipedia HomePage Clone/wikimedia-foundation.jpg
  Wikipedia HomePage Clone/wikinews.png
  Wikipedia HomePage Clone/wikiquote.png
  Wikipedia HomePage Clone/wikisource.png
  Wikipedia HomePage Clone/wikispecies.png
  Wikipedia HomePage Clone/wikiversity.png
  Wikipedia HomePage Clone/wikivoyage.png
  Wikipedia HomePage Clone/wiktionary.jpg
Labels: GSSoC22

#312 spacex-page
  .DS_Store
  spacex/css/footer.css
  spacex/css/hamburger.css
  spacex/css/header.css
  spacex/css/mission.css
  spacex/css/navigation.css
  spacex/css/reset.css
  spacex/css/responsive.css
  spacex/index.html
  spacex/js/index.js
  spacex/media/1.webp
  spacex/media/2.webp
  spacex/media/3.webp
  spacex/media/4.webp
  spacex/media/5.webp
  spacex/media/logos/spacex-logo.png
Labels: GSSoC22

#280 Added Nykaa Clone
  Nykaa Clone/Home Page/Home.css
  Nykaa Clone/Home Page/Home.html
  Nykaa Clone/Home Page/Home.js
  Nykaa Clone/Home Page/Images/img1.jpg
  Nykaa Clone/Home Page/Images/img2.jpg
  Nykaa Clone/Home Page/Images/img3.jpg
  Nykaa Clone/Home Page/Images/img4.jpg
  Nykaa Clone/Home Page/Images/img5.jpg
  Nykaa Clone/Kids Page/Images/img1.jpg
  Nykaa Clone/Kids Page/Images/img2.jpg
  Nykaa Clone/Kids Page/Images/img3.jpg
  Nykaa Clone/Kids Page/Images/img4.jpg
  Nykaa Clone/Kids Page/Images/img5.jpg
  Nykaa Clone/Kids Page/Kids.css
  Nykaa Clone/Kids Page/Kids.html
  Nykaa Clone/Kids Page/Kids.js
  Nykaa Clone/LandingPage/LandingPage.css
  Nykaa Clone/LandingPage/LandingPage.js
  Nykaa Clone/LandingPage/index.html
  Nykaa Clone/Payment Page/Payment.css
  Nykaa Clone/Payment Page/Payment.html
  Nykaa Clone/Payment Page/Payment.js
  Nykaa Clone/Payment Page/PaymentPage2/Payment2.css
  Nykaa Clone/Payment Page/PaymentPage2/Payment2.html
  Nykaa Clone/Payment Page/PaymentPage2/Payment2.js
  Nykaa Clone/Payment Page/PaymentPage2/delivery3.jpg
  Nykaa Clone/Payment Page/PaymentPage2/download.png
  Nykaa Clone/Payment Page/nykaa-logo.png
  Nykaa Clone/ProductDetails/Product.css
  Nykaa Clone/ProductDetails/Product.html
  Nykaa Clone/ProductDetails/Product.js
  Nykaa Clone/ProductDetails/navbar.css
  Nykaa Clone/Tech page/Tech.css
  Nykaa Clone/Tech page/Tech.html
  Nykaa Clone/Tech page/Tech.js
  Nykaa Clone/Tech page/images/img1.jpg
  Nykaa Clone/Tech page/images/img2.jpg
  Nykaa Clone/Tech page/images/img3.jpg
  Nykaa Clone/Tech page/images/img4.jpg
  Nykaa Clone/Tech page/images/img5.jpg
  Nykaa Clone/menpage/men.css
  Nykaa Clone/menpage/men.html
  Nykaa Clone/menpage/men.js
  Nykaa Clone/womanpage/woman.css
  Nykaa Clone/womanpage/woman.html
  Nykaa Clone/womanpage/woman.js
  Nykaa Clone/womanpage/woman2.css
  Nykaa Clone/womanpage/woman2.js
Labels: Level2, GSSoC22

#326 Made git clone responsive
  .DS_Store
  .github/.DS_Store
  2048 Clone/.DS_Store
  AirBnb WebPage Clone/styles.css
  Codepen-Clone/.DS_Store
  Discord_App_Clone/.DS_Store
  Discord_App_Clone/assets/css/bootstrap.css
  Discord_App_Clone/assets/css/bootstrap.css.map
  Discord_App_Clone/assets/css/style.css
  Discord_App_Clone/home.html
  FAQ-PAGE/.DS_Store
  FAQ-PAGE/bootstrap/dist/css/bootstrap-grid.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-grid.min.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-grid.min.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap-grid.rtl.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-grid.rtl.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap-reboot.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-reboot.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap-reboot.min.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-reboot.rtl.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap-reboot.rtl.min.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-utilities.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-utilities.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap-utilities.min.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-utilities.rtl.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap-utilities.rtl.min.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap-utilities.rtl.min.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap.min.css.map
  FAQ-PAGE/bootstrap/dist/css/bootstrap.rtl.css
  FAQ-PAGE/bootstrap/dist/css/bootstrap.rtl.min.css
  FAQ-PAGE/bootstrap/scss/_navbar.scss
  FAQ-PAGE/bootstrap/scss/_reboot.scss
  FAQ-PAGE/bootstrap/scss/mixins/_utilities.scss
  FAQ-PAGE/bootstrap/scss/mixins/_visually-hidden.scss
  FAQ-PAGE/styles.css
  FLIPKART-CLONE/style.css
  Github_Homepage_Clone/assets/css/home.css
  Github_Homepage_Clone/assets/css/style.css
  Github_Homepage_Clone/index.html
  Google-Search-Engine-Clone/src/Search.css
  Instagram_Clone/style.css
  KFC-Clone/.DS_Store
  KFC-Clone/style.css
  Mac OS Clone/.DS_Store
  Microsoft_Teams_Page_Clone/.DS_Store
  NETFLIX-CLONE/.DS_Store
  PLURALSIGHT Clone/.DS_Store
  PLURALSIGHT Clone/styles/index.css
  SLACK-CLONE/.DS_Store
  SLACK-CLONE/src/App.css
  SLACK-CLONE/src/components/sidebar/Channels/Channels.css
  SLACK-CLONE/src/components/sidebar/sidebar.css
  SPOTIFY-CLONE/.DS_Store
  Tesla/.DS_Store
  Uber Eats Clone/.DS_Store
  Wordle_Clone/style.css
  ZOOM-CLONE/.DS_Store
  hulu-webpage-clone/.DS_Store
  index.css
Labels: Level1, GSSoC22

#328 Disney Plus UI Clone
  Disney Plus Clone/README.md
  Disney Plus Clone/app.js
  Disney Plus Clone/images/add.png
  Disney Plus Clone/images/disney.PNG
  Disney Plus Clone/images/geographic.PNG
  Disney Plus Clone/images/logo.png
  Disney Plus Clone/images/marvel.PNG
  Disney Plus Clone/images/nxt.png
  Disney Plus Clone/images/pixar.PNG
  Disney Plus Clone/images/play.png
  Disney Plus Clone/images/poster 1.png
  Disney Plus Clone/images/poster 10.png
  Disney Plus Clone/images/poster 11.png
  Disney Plus Clone/images/poster 12.png
  Disney Plus Clone/images/poster 2.png
  Disney Plus Clone/images/poster 3.png
  Disney Plus Clone/images/poster 4.png
  Disney Plus Clone/images/poster 5.png
  Disney Plus Clone/images/poster 6.png
  Disney Plus Clone/images/poster 7.png
  Disney Plus Clone/images/poster 8.png
  Disney Plus Clone/images/poster 9.png
  Disney Plus Clone/images/pre.png
  Disney Plus Clone/images/slider 1.PNG
  Disney Plus Clone/images/slider 2.PNG
  Disney Plus Clone/images/slider 3.PNG
  Disney Plus Clone/images/slider 4.PNG
  Disney Plus Clone/images/slider 5.PNG
  Disney Plus Clone/images/star-wars.PNG
  Disney Plus Clone/index.html
  Disney Plus Clone/script.js
  Disney Plus Clone/style.css
  Disney Plus Clone/videos/disney.mp4
  Disney Plus Clone/videos/geographic.mp4
  Disney Plus Clone/videos/marvel.mp4
  Disney Plus Clone/videos/pixar.mp4
  Disney Plus Clone/videos/star-war.mp4
Labels: GSSoC22, Level3

#327 Connectivity done of the Instagram Clone with its Login Page Clone
  Instagram_Clone/login.html
Labels: GSSoC22

#334 Space-X Landing Page Clone
  README.md
  Spacx Landing-Page Clone/Readme.md
  Spacx Landing-Page Clone/assets/favicon.ico
  Spacx Landing-Page Clone/assets/img-1.jpg
  Spacx Landing-Page Clone/assets/img-2.jpg
  Spacx Landing-Page Clone/assets/img-3.webp
  Spacx Landing-Page Clone/assets/img-4.jpg
  Spacx Landing-Page Clone/assets/img-5.webp
  Spacx Landing-Page Clone/assets/spacex-logo.png
  Spacx Landing-Page Clone/basic.css
  Spacx Landing-Page Clone/index.html
  Spacx Landing-Page Clone/output ss/1.png
  Spacx Landing-Page Clone/output ss/2.png
  Spacx Landing-Page Clone/output ss/3.png
  Spacx Landing-Page Clone/output ss/4.png
  Spacx Landing-Page Clone/output ss/Responsive Checking 1.png
  Spacx Landing-Page Clone/output ss/Responsive Checking 2.png
  Spacx Landing-Page Clone/output ss/Responsive Checking 3.png
  Spacx Landing-Page Clone/script.js
  Spacx Landing-Page Clone/style.css
Labels: Level2, GSSoC22

#337 w3schools landing page
  W3 schools frontend/CurveOfheader.png
  W3 schools frontend/README.md
  W3 schools frontend/container.css
  W3 schools frontend/header.css
  W3 schools frontend/html_1.png
  W3 schools frontend/index.html
  W3 schools frontend/index.js
  W3 schools frontend/nav-icons.png
  W3 schools frontend/nav.css
Labels: GSSoC22, Level3

#317 Added Footer section for Zomato
  Zomato_Homepage_Clone/package-lock.json
  Zomato_Homepage_Clone/package.json
  Zomato_Homepage_Clone/src/components/common/Footer/Footer.css
  Zomato_Homepage_Clone/src/components/common/Footer/index.js
  Zomato_Homepage_Clone/src/components/common/Footer/zomato.png
  Zomato_Homepage_Clone/src/index.css
Labels: Level2, GSSoC22

#325 modify navbar to be more responsive
  index.css
  index.html
Labels: GSSoC22

#340 Added zara clone webpade
  .DS_Store
  zara/index.html
  zara/scripts.js
  zara/style.css
Labels: GSSoC22

#341 Adding Mentor Section and link for repo contributors
  README.md
Labels: Level1, GSSoC22

#356 added more websites in the cloneit website
  assets/pinterest.png
  assets/wikipedia.jpeg
  assets/zara.png
  index.css
  index.html
  spacex/css/footer.css
  spacex/css/hamburger.css
  spacex/css/header.css
  spacex/css/mission.css
  spacex/css/navigation.css
  spacex/css/reset.css
  spacex/css/responsive.css
  spacex/index.html
  spacex/js/index.js
  spacex/media/1.webp
  spacex/media/2.webp
  spacex/media/3.webp
  spacex/media/4.webp
  spacex/media/5.webp
  spacex/media/logos/spacex-logo.png
Labels: GSSoC22

#357 updated cloneit website
  .DS_Store
  assets/w3school.png
  assets/whatsapp.jpeg
  index.css
  index.html
Labels: Level1, GSSoC22

#363 Navbar and Footer of FAQ page fixed
  FAQ-PAGE/faq.html
  FAQ-PAGE/styles.css
  index.css
Labels: GSSoC22

#360 Added OLX Clone
  OLX Clone/Images/Ad.png
  OLX Clone/Images/Download.png
  OLX Clone/Images/Fan.png
  OLX Clone/Images/MyImage.png
  OLX Clone/Images/Playstore.png
  OLX Clone/Images/Tv.png
  OLX Clone/Images/Tv1.png
  OLX Clone/Images/keyboard.png
  OLX Clone/Images/logo.png
  OLX Clone/Images/mouse.png
  OLX Clone/Images/printer.png
  OLX Clone/Images/product1.png
  OLX Clone/Images/product2.png
  OLX Clone/Readme.md
  OLX Clone/index.html
  OLX Clone/script.js
  OLX Clone/style.css
Labels: Level2, GSSoC22

#330 Added tinder clone
  Tinder clone/css/style.css
  Tinder clone/img/hirtik roshan.jpg
  Tinder clone/img/loader.gif
  Tinder clone/index.html
  Tinder clone/logo.png
  Tinder clone/tinder-heat.png
Labels: GSSoC22

#370 logo fixed
  .vs/Clone-IT/v17/.suo
  .vs/slnx.sqlite
  assets/Zara_Logo.svg
  assets/wikipedia.svg
  index.css
Labels: fixed

#372 SpaceX clone
  SpaceX_Clone/README.md
  SpaceX_Clone/images/1.jpg
  SpaceX_Clone/images/2.jpg
  SpaceX_Clone/images/2.webp
  SpaceX_Clone/images/3.jpg
  SpaceX_Clone/images/4.jpg
  SpaceX_Clone/images/5.jpg
  SpaceX_Clone/images/logo.jpg
  SpaceX_Clone/images/s.ico
  SpaceX_Clone/images/spacex.png
  SpaceX_Clone/index.html
  SpaceX_Clone/script.js
  SpaceX_Clone/styles.css
Labels: Level2, GSSoC22

#374 Freshworks clone
  FreshWorks-clone/favicon.ico
  FreshWorks-clone/index.html
  FreshWorks-clone/mail.png
  FreshWorks-clone/styles.css
Labels: Level1, GSSoC22

#386 Added hackerRank clone
  HackerRank Clone/Images/AI.svg
  HackerRank Clone/Images/Algorithm.svg
  HackerRank Clone/Images/C++.svg
  HackerRank Clone/Images/C.svg
  HackerRank Clone/Images/DataBase.svg
  HackerRank Clone/Images/DataStructure.svg
  HackerRank Clone/Images/FunctionalProgramming.svg
  HackerRank Clone/Images/Java.svg
  HackerRank Clone/Images/LinuxShell.svg
  HackerRank Clone/Images/Mathematics.svg
  HackerRank Clone/Images/Python.svg
  HackerRank Clone/Images/Ruby.svg
  HackerRank Clone/Images/SQL.svg
  HackerRank Clone/Images/delete.html
  HackerRank Clone/Images/heading.svg
  HackerRank Clone/Images/regex.svg
  HackerRank Clone/Readme.md
  HackerRank Clone/index.html
  HackerRank Clone/style.css
Labels: Level2, GSSoC22

#385 Improved about us section
  index.css
Labels: Level1, GSSoC22

#383 Added Amazon Prime Home Page Clone
  Amazon Prime Home Page Clone/prime video.html
  Amazon Prime Home Page Clone/prime video_files/01j6Cy0Aa2L.css
  Amazon Prime Home Page Clone/prime video_files/01jO3dgXnDL.css
  Amazon Prime Home Page Clone/prime video_files/01vPAGooc1L.css
  Amazon Prime Home Page Clone/prime video_files/11EIQ5IGqaL._RC_01ZTHTZObnL.css,41wZkyTaWoL.css,31Y8m1dzTdL.css,013z33uKh2L.css,017DsKjNQJL.css,0131vqwP5UL.css,41EWOOlBJ9L.css,11TIuySqr6L.css,01ElnPiDxWL.css,11bGSgD5pDL.css,01Dm5eKVxwL.css,01IdKcBuAdL..css
  Amazon Prime Home Page Clone/prime video_files/11FbwVANcKL.js.download
  Amazon Prime Home Page Clone/prime video_files/214FMPLrWwL.js.download
  Amazon Prime Home Page Clone/prime video_files/21Op85HkAuL.css
  Amazon Prime Home Page Clone/prime video_files/31BNlIxMFGL.js.download
  Amazon Prime Home Page Clone/prime video_files/31OVaxqP8wL.js.download
  Amazon Prime Home Page Clone/prime video_files/41J-chR6LCL.js.download
  Amazon Prime Home Page Clone/prime video_files/41QXBib8ExL.css
  Amazon Prime Home Page Clone/prime video_files/41RjTA0hp7L.js.download
  Amazon Prime Home Page Clone/prime video_files/41cm85WNwyL.js.download
  Amazon Prime Home Page Clone/prime video_files/41hb9nUcQdL._RC_11gtQwARADL.css,51lMIbQoSSL.css_.css
  Amazon Prime Home Page Clone/prime video_files/426x294_Discovery.jpg
  Amazon Prime Home Page Clone/prime video_files/426x294_MANORAMAMAX.jpg
  Amazon Prime Home Page Clone/prime video_files/515fxSyOlEL.js.download
  Amazon Prime Home Page Clone/prime video_files/51odQIWqZYL.js.download
  Amazon Prime Home Page Clone/prime video_files/61IX-E1-BRL.css
  Amazon Prime Home Page Clone/prime video_files/61XKxrBtDVL._RC_11Y+5x+kkTL.js,51106gSDnJL.js,11yKORv-GTL.js,11giXtZCwVL.js,01+z+uIeJ-L.js,01VRMV3FBdL.js,21SDJtBU-PL.js,012FVc3131L.js,11rRjDLdAVL.js,51H19hJRYrL.js,11kWu3cNjYL.js,11tMohjWmVL.js,11O.download
  Amazon Prime Home Page Clone/prime video_files/71-R5U8Pt5L.css
  Amazon Prime Home Page Clone/prime video_files/71PTLyoHYXL.js.download
  Amazon Prime Home Page Clone/prime video_files/71er6ighcOL.js.download
  Amazon Prime Home Page Clone/prime video_files/71j725ozkHL.css
  Amazon Prime Home Page Clone/prime video_files/71zbqEZA8QL.js.download
  Amazon Prime Home Page Clone/prime video_files/8148mZV0xwL.js.download
  Amazon Prime Home Page Clone/prime video_files/81EwPX8K-SL.js.download
  Amazon Prime Home Page Clone/prime video_files/81wwyivMVhL.js.download
  Amazon Prime Home Page Clone/prime video_files/A2MFUE2XK8ZSSY_262-4395704-7610519_XE6PY40TE047AP1GJGSF$uedata=s__rd_uedata_staticb&id=XE6PY40TE047AP1GJGSF&pty=DVSignupOffer&spty=nonprimehomepage&pti=HO-null_1000
  Amazon Prime Home Page Clone/prime video_files/Docubay-426X2947_V1.jpg
  Amazon Prime Home Page Clone/prime video_files/Erosnow-426X2948_V1.jpg
  Amazon Prime Home Page Clone/prime video_files/Hayu_logo_for_MLP_Grid.jpg
  Amazon Prime Home Page Clone/prime video_files/LionsgatePlay-426X2946_V1.jpg
  Amazon Prime Home Page Clone/prime video_files/Mubi-426X2946_V1.jpg
  Amazon Prime Home Page Clone/prime video_files/ShortsTV-426X2944_V1.jpg
  Amazon Prime Home Page Clone/prime video_files/hoichoi-426X2946_V1.jpg
  Amazon Prime Home Page Clone/prime video_files/web_footer_logo._CB462908456_.png
  Amazon Prime Home Page Clone/readme
Labels: Level2, GSSoC22

#390 Added Food Panda Cloned Website
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/Bangladesh.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/HK-1.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/HU.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/MY.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/PH.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/PK.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/SG-1.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/SK.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/TH.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/TW.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/analytics-talk-content-tracking.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/analytics.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/bootstrap.min.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/bootstrap.min.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/bst.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/bst.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/cambodia-e1582274460360.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/embed.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/font-awesome.min.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/food-panda-logo-vector.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/foodpanda-rider-opt.jpg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/foodpanda-tuna-opt-scaled.jpg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/gtm.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/gtm4wp-youtube.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/ic_social_facebook.svg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/ic_social_linkedin.svg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/iframe_api
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/jquery.min.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/laos-e1582274407429.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/modernizr-2.8.3.min.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/myanmar-e1582274330314.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/parallax.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/romania.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/style.min.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/styles.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/team_bg-opt.jpg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/vuu2uob.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/wp-emoji-release.min.js.download
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/www-widgetapi.js.download
  Food Panda Website Clone/index.html
  Food Panda Website Clone/readme
Labels: Level2, GSSoC22

#354 Adding swiggy clone
  Swiggy-clone/README.md
  Swiggy-clone/style.css
  Swiggy-clone/swiggy.html
Labels: Level1, GSSoC22

#369 Changes in flipkart clone
  FLIPKART-CLONE/index.html
  FLIPKART-CLONE/script.js
  FLIPKART-CLONE/style.css
Labels: Level1, GSSoC22

#399 Added Girlscript Summer Of Code(GSSoC) Website Clone
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India.html
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/105-76f8eb18e7dd0f39.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/151416170-51c1f8ec-28bd-41b0-bf9c-837509e5460e.png
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/152588880-e94c9c2f-b16b-4a29-859e-503b6232709c.png
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/152650042-40a281d5-4bdc-40a0-bd06-d907023f1a04.png
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/152650045-df82c3ea-e3ac-4bf2-acaa-14d80729384d.png
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/152650376-d285b39d-3b06-4c46-afad-c15b90074358.svg
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/412-1b326a7359d60af4.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/527-c605b7b1f85ba18c.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/69f81e06845cd7ae.css
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/763d8acbc2e939e6.css
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/814-ac3f288bc29ede5c.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/93-f84e6bec986a5cd6.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/GS_logo_Black1.png
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/_app-985ea3b28451022e.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/_buildManifest.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/_middlewareManifest.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/_ssgManifest.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/a9a7754c-c441188dc9d7c816.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/codeofconduct-bbe6addc4e854298.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/faq-3500c0c96022a776.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/framework-91d7f78b5b4003c8.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/index-7e273765384acba4.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/leaderboard-9a71de41d04f970c.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/main-e47bb435dabe4202.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/polyfills-5cd94c89d3acac5f.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/project-8652d4e98bfcf558.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/schedule-c91750ecf61d0f16.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/team-65103507be851f1e.js.download
  Girlscript Summer Of Code Website Clone/GirlScipt Summer of Code 2022 _ GirlScript Foundation India_files/webpack-378e68e29c265886.js.download
  Girlscript Summer Of Code Website Clone/readme
Labels: Level2, GSSoC22

#398 Added Rapido Bike Taxi Website Clone
  Rapido Bike Taxi Website Clone/Rapido.html
  Rapido Bike Taxi Website Clone/Rapido_files/3615fd59-a79c-485a-adb8-63d5d52fac06.png
  Rapido Bike Taxi Website Clone/Rapido_files/49e699db-bdfb-4978-97bb-46533d982a1b.png
  Rapido Bike Taxi Website Clone/Rapido_files/CCcare_1.webp
  Rapido Bike Taxi Website Clone/Rapido_files/CCcare_2.webp
  Rapido Bike Taxi Website Clone/Rapido_files/CCcare_3.webp
  Rapido Bike Taxi Website Clone/Rapido_files/Rapido4business1.png
  Rapido Bike Taxi Website Clone/Rapido_files/Rapido4business2.png
  Rapido Bike Taxi Website Clone/Rapido_files/_app.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/app_store.svg
  Rapido Bike Taxi Website Clone/Rapido_files/captain_care_1.webp
  Rapido Bike Taxi Website Clone/Rapido_files/captain_care_2.webp
  Rapido Bike Taxi Website Clone/Rapido_files/captain_care_3.webp
  Rapido Bike Taxi Website Clone/Rapido_files/commons.a117a371.chunk.css
  Rapido Bike Taxi Website Clone/Rapido_files/commons.dad0a0942e2d87029cfe.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/css
  Rapido Bike Taxi Website Clone/Rapido_files/down-arrow.svg
  Rapido Bike Taxi Website Clone/Rapido_files/f(1).txt
  Rapido Bike Taxi Website Clone/Rapido_files/f.txt
  Rapido Bike Taxi Website Clone/Rapido_files/fbevents.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/g_p.svg
  Rapido Bike Taxi Website Clone/Rapido_files/gtm.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/home_img_new.webp
  Rapido Bike Taxi Website Clone/Rapido_files/index.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/insight.min.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/js
  Rapido Bike Taxi Website Clone/Rapido_files/logo.svg
  Rapido Bike Taxi Website Clone/Rapido_files/main-398368813911ff87f094.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/play_store.svg
  Rapido Bike Taxi Website Clone/Rapido_files/polyfills-8cf63c2824ab67885018.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/presence_1.webp
  Rapido Bike Taxi Website Clone/Rapido_files/presence_2.webp
  Rapido Bike Taxi Website Clone/Rapido_files/presence_3.webp
  Rapido Bike Taxi Website Clone/Rapido_files/presence_4.webp
  Rapido Bike Taxi Website Clone/Rapido_files/saved_resource
  Rapido Bike Taxi Website Clone/Rapido_files/styles.37374e25dbcaf93e6fa1.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/styles.a441bdc2.chunk.css
  Rapido Bike Taxi Website Clone/Rapido_files/webpack-4b444dab214c6491079c.js.download
  Rapido Bike Taxi Website Clone/Rapido_files/who_we_1.webp
  Rapido Bike Taxi Website Clone/Rapido_files/who_we_2.webp
  Rapido Bike Taxi Website Clone/Rapido_files/y_p.svg
  Rapido Bike Taxi Website Clone/readme
Labels: GSSoC22

#416 NVIDIA Clone
  NVIDIA_Clone/README.md
  NVIDIA_Clone/images/0.jpg
  NVIDIA_Clone/images/1.jpg
  NVIDIA_Clone/images/10.jpg
  NVIDIA_Clone/images/11.jpg
  NVIDIA_Clone/images/12.jpg
  NVIDIA_Clone/images/13.jpg
  NVIDIA_Clone/images/14.jpg
  NVIDIA_Clone/images/2.jpg
  NVIDIA_Clone/images/3.jpg
  NVIDIA_Clone/images/4.jpg
  NVIDIA_Clone/images/5.jpg
  NVIDIA_Clone/images/6.jpg
  NVIDIA_Clone/images/7.jpg
  NVIDIA_Clone/images/8.jpg
  NVIDIA_Clone/images/9.jpg
  NVIDIA_Clone/images/favicon.ico
  NVIDIA_Clone/images/logo.png
  NVIDIA_Clone/images/n.png
  NVIDIA_Clone/index.html
  NVIDIA_Clone/script.js
  NVIDIA_Clone/styles.css
Labels: Level1, GSSoC22

#417 Added Jet brains Website Clone
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/Frans-Bouma@2x.png
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/Marvin-Burman@2x.png
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/Mary-Grygleski@2x.png
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/annual-highlights-icon.svg
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/banner_home-play_black.svg
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/banner_home-survey.svg
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/css1.css
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/css2.css
  Jet Brains Website Clone/JetBrains_ Essential tools for software developers and teams_files/css3.css
  Jet Brains Website Clone/index.html
  Jet Brains Website Clone/readme
Labels: Level1, GSSoC22

#414 Added Hackerearth clone
  HackerEarth Clone/For developers - Resources for technical recruitment_files/back-button.svg
  HackerEarth Clone/For developers - Resources for technical recruitment_files/codeexplained.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/compete-icon.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/compete.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/he-footer-logo.svg
  HackerEarth Clone/For developers - Resources for technical recruitment_files/he-header-logo.svg
  HackerEarth Clone/For developers - Resources for technical recruitment_files/he-mobile-logo.svg
  HackerEarth Clone/For developers - Resources for technical recruitment_files/interview-ready.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/join-icon.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/join.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/leaderboard.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/learn-icon.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/learn.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/programming-ability.png
  HackerEarth Clone/For developers - Resources for technical recruitment_files/style.css
  HackerEarth Clone/index.html
  HackerEarth Clone/readme
Labels: Level1, GSSoC22
