Repository Rayman-Sodhi/Clone-IT, pull requests merged in 2022-03, with the labels that each got.

#93 Added slack clone
  README.md
  SLACK-CLONE/README.md
  SLACK-CLONE/package-lock.json
  SLACK-CLONE/package.json
  SLACK-CLONE/public/index.html
  SLACK-CLONE/public/manifest.json
  SLACK-CLONE/public/robots.txt
  SLACK-CLONE/public/slack.png
  SLACK-CLONE/src/App.css
  SLACK-CLONE/src/App.js
  SLACK-CLONE/src/components/Auth/Auth.css
  SLACK-CLONE/src/components/Auth/Login.jsx
  SLACK-CLONE/src/components/Auth/Register.jsx
  SLACK-CLONE/src/components/Messages/ImageUpload/ImageUpload.js
  SLACK-CLONE/src/components/Messages/Messages.css
  SLACK-CLONE/src/components/Messages/Messages.js
  SLACK-CLONE/src/components/Messages/messageContent/MessageContent.js
  SLACK-CLONE/src/components/Messages/messageContent/messageContent.css
  SLACK-CLONE/src/components/Messages/messageHeader/MessageHeader.js
  SLACK-CLONE/src/components/Messages/messageInput/MessageInput.js
  SLACK-CLONE/src/components/sidebar/Channels/Channels.css
  SLACK-CLONE/src/components/sidebar/Channels/Channels.js
  SLACK-CLONE/src/components/sidebar/Favourites/FavouriteChannel.js
  SLACK-CLONE/src/components/sidebar/Sidebar.js
  SLACK-CLONE/src/components/sidebar/UserInfo/UserInfo.css
  SLACK-CLONE/src/components/sidebar/UserInfo/UserInfo.js
  SLACK-CLONE/src/components/sidebar/privateChat/PrivateChat.js
  SLACK-CLONE/src/components/sidebar/sidebar.css
  SLACK-CLONE/src/images/downlogo.png
  SLACK-CLONE/src/images/sidelogo.png
  SLACK-CLONE/src/images/sidelogo1.png
  SLACK-CLONE/src/images/slack.png
  SLACK-CLONE/src/images/ss.png
  SLACK-CLONE/src/index.css
  SLACK-CLONE/src/index.js
  SLACK-CLONE/src/server/firebase.js
  SLACK-CLONE/src/store/actioncreator.js
  SLACK-CLONE/src/store/actiontypes.js
  SLACK-CLONE/src/store/reducer.js
Labels: GSSoC22, Level1

#83 google keep notes clone (add new clone website)
  GOOGLE-KEEP-CLONE/.gitignore
  GOOGLE-KEEP-CLONE/README.md
  GOOGLE-KEEP-CLONE/package-lock.json
  GOOGLE-KEEP-CLONE/package.json
  GOOGLE-KEEP-CLONE/public/index.html
  GOOGLE-KEEP-CLONE/public/manifest.json
  GOOGLE-KEEP-CLONE/public/robots.txt
  GOOGLE-KEEP-CLONE/src/App.js
  GOOGLE-KEEP-CLONE/src/CreateNote.js
  GOOGLE-KEEP-CLONE/src/Footer.js
  GOOGLE-KEEP-CLONE/src/Header.js
  GOOGLE-KEEP-CLONE/src/Note.js
  GOOGLE-KEEP-CLONE/src/index.js
  GOOGLE-KEEP-CLONE/src/style.css
  README.md
Labels: GSSoC22, Level1

#103 Projects link added to website
  assets/facebook.png
  assets/google-keep.png
  assets/google.png
  assets/slack.png
  assets/youtube.svg
  index.css
  index.html
Labels: GSSoC22, Level1

#107 Added apple clone
  Apple-clone/images/img1.jpeg
  Apple-clone/images/img2.jpeg
  Apple-clone/images/img3.jpg
  Apple-clone/images/img4.jpeg
  Apple-clone/images/img5.jpeg
  Apple-clone/images/img6.jpg
  Apple-clone/images/img7.jpeg
  Apple-clone/images/img8.jpg
  Apple-clone/images/img9.jpg
  Apple-clone/images/logo.png
  Apple-clone/images/txtimg1.png
  Apple-clone/images/txtimg2.png
  Apple-clone/images/txtimg3.png
  Apple-clone/images/txtimg4.png
  Apple-clone/index.html
  Apple-clone/style.css
  README.md
  assets/apple.jpg
  index.css
  index.html
Labels: GSSoC22, Level1

#110 Apple Clone linked in website
  assets/apple.png
  index.css
  index.html
Labels: GSSoC22, Level1

#100 Added Starbucks clone
  README.md
  index.css
  index.html
  starbucks clone/index.html
  starbucks clone/previewstarbucks.png
  starbucks clone/starbucks img 1.png
  starbucks clone/starbucks img 10.png
  starbucks clone/starbucks img 2.png
  starbucks clone/starbucks img 3.png
  starbucks clone/starbucks img 4.png
  starbucks clone/starbucks img 5.png
  starbucks clone/starbucks img 6.png
  starbucks clone/starbucks img 7.png
  starbucks clone/starbucks img 8.png
  starbucks clone/starbucks img 9.png
  starbucks clone/starbucks logo.png
  starbucks clone/starbucks main logo.png
  starbucks clone/style.css
Labels: GSSoC22, Level1

#124 Starbucks added in website and arranged correctly
  assets/starbucks.png
  index.css
  index.html
Labels: GSSoC22, Level1

#127 workflows added
  .github/workflows/Auto_message_on_pr_open.yml
  .github/workflows/issue-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: enhancement

#90 Added code for youtube clone
  YOUTUBE-CLONE/Images/Images/1.png.png
  YOUTUBE-CLONE/Images/Images/11.png
  YOUTUBE-CLONE/Images/Images/2.png
  YOUTUBE-CLONE/Images/Images/22.png
  YOUTUBE-CLONE/Images/Images/3.png
  YOUTUBE-CLONE/Images/Images/33.png
  YOUTUBE-CLONE/Images/Images/4.png
  YOUTUBE-CLONE/Images/Images/44.png
  YOUTUBE-CLONE/Images/Images/5.png
  YOUTUBE-CLONE/Images/Images/6.png
  YOUTUBE-CLONE/Images/Images/7.png
  YOUTUBE-CLONE/Images/Images/8.png
  YOUTUBE-CLONE/Images/Images/88.png
  YOUTUBE-CLONE/Images/Images/9.png
  YOUTUBE-CLONE/README.md
  YOUTUBE-CLONE/index.html
  YOUTUBE-CLONE/style.css
Labels: GSSoC22, Level 1

#133 Update README.md
  README.md
Labels: GSSoC22, Level 1

#134 Issueform
  .github/ISSUE_TEMPLATE/Bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .gitignore
Labels: GSSoC22, Level 2

#98 Added GitHub homepage clone
  Github_Homepage_Clone/assets/css/style.css
  Github_Homepage_Clone/assets/media/Capture.PNG
  Github_Homepage_Clone/assets/media/person.jfif
  Github_Homepage_Clone/index.html
  README.md
Labels: GSSoC22, Level 1

#135 Add Description about GSSOC in main website About Us section .
  assets/GSSOC.png
  index.html
Labels: GSSoC22, Level 1

#136 Github Homepage Clone linked on site
  assets/Github.jpg
  assets/github.svg
  assets/google.webp
  assets/swoc.png
  index.css
  index.html
Labels: GSSoC 22

#143 Add Search Button for the Projects section
  index.css
  index.html
Labels: GSSoC22, Level 2

#145 Add Search Button in Projects Section
  index.css
  index.html
Labels: Level 1, GSSoC 22

#147 Quora Clone Added
  QUORA-CLONE/assets/Images/32048.webp
  QUORA-CLONE/assets/Images/Background.png
  QUORA-CLONE/assets/Images/image10.webp
  QUORA-CLONE/assets/Images/image11.jpeg
  QUORA-CLONE/assets/Images/image12.jpg
  QUORA-CLONE/assets/Images/image13.jpg
  QUORA-CLONE/assets/Images/image14.webp
  QUORA-CLONE/assets/Images/image15.webp
  QUORA-CLONE/assets/Images/image2.jpg
  QUORA-CLONE/assets/Images/image3.avif
  QUORA-CLONE/assets/Images/image4.jpeg
  QUORA-CLONE/assets/Images/image5.webp
  QUORA-CLONE/assets/Images/image6.webp
  QUORA-CLONE/assets/Images/image7.webp
  QUORA-CLONE/assets/Images/image8.webp
  QUORA-CLONE/assets/Images/image9.jpg
  QUORA-CLONE/assets/css/all.css
  QUORA-CLONE/assets/css/all.min.css
  QUORA-CLONE/assets/css/brands.css
  QUORA-CLONE/assets/css/brands.min.css
  QUORA-CLONE/assets/css/fontawesome.css
  QUORA-CLONE/assets/css/fontawesome.min.css
  QUORA-CLONE/assets/css/regular.css
  QUORA-CLONE/assets/css/regular.min.css
  QUORA-CLONE/assets/css/solid.css
  QUORA-CLONE/assets/css/solid.min.css
  QUORA-CLONE/assets/css/svg-with-js.css
  QUORA-CLONE/assets/css/svg-with-js.min.css
  QUORA-CLONE/assets/css/v4-font-face.css
  QUORA-CLONE/assets/css/v4-font-face.min.css
  QUORA-CLONE/assets/css/v4-shims.css
  QUORA-CLONE/assets/css/v4-shims.min.css
  QUORA-CLONE/assets/css/v5-font-face.css
  QUORA-CLONE/assets/css/v5-font-face.min.css
  QUORA-CLONE/assets/webfonts/fa-brands-400.ttf
  QUORA-CLONE/assets/webfonts/fa-brands-400.woff2
  QUORA-CLONE/assets/webfonts/fa-regular-400.ttf
  QUORA-CLONE/assets/webfonts/fa-regular-400.woff2
  QUORA-CLONE/assets/webfonts/fa-solid-900.ttf
  QUORA-CLONE/assets/webfonts/fa-solid-900.woff2
  QUORA-CLONE/assets/webfonts/fa-v4compatibility.ttf
  QUORA-CLONE/assets/webfonts/fa-v4compatibility.woff2
  QUORA-CLONE/index.html
  QUORA-CLONE/style.css
  README.md
Labels: Level 1, GSSoC 22

#159 Added Unsplash Clone
  README.md
  UNSPLASH-CLONE/index.html
  UNSPLASH-CLONE/script.js
  UNSPLASH-CLONE/search.css
  UNSPLASH-CLONE/search.html
  UNSPLASH-CLONE/style.css
Labels: Level 2, GSSoC 22

#162 Readme updated
  index.html
Labels: bug, fixed

#169 PLURALSIGHT WebPage Clone
  PLURALSIGHT Clone/IMAGES/.DS_Store
  PLURALSIGHT Clone/IMAGES/50 free.png
  PLURALSIGHT Clone/IMAGES/Cloud-labs-image2x.png
  PLURALSIGHT Clone/IMAGES/Twitter_Icon.svg
  PLURALSIGHT Clone/IMAGES/adobe.png
  PLURALSIGHT Clone/IMAGES/adp.png
  PLURALSIGHT Clone/IMAGES/angular-14a0f6532f.png
  PLURALSIGHT Clone/IMAGES/certification-prep.png
  PLURALSIGHT Clone/IMAGES/csharp-e7b8fcd4ce.png
  PLURALSIGHT Clone/IMAGES/delivery-module.png
  PLURALSIGHT Clone/IMAGES/flow-demo-thumbnail.png
  PLURALSIGHT Clone/IMAGES/from soldier to.png
  PLURALSIGHT Clone/IMAGES/fujitsu.png
  PLURALSIGHT Clone/IMAGES/globe-white.png
  PLURALSIGHT Clone/IMAGES/javascript-542e10ea6e.png
  PLURALSIGHT Clone/IMAGES/kisspng-farmington-amazon-com-pluralsight-technology-learn-5b08606a2bb882.6684082415272756261791.png
  PLURALSIGHT Clone/IMAGES/logo-skills.png
  PLURALSIGHT Clone/IMAGES/nasdaq.png
  PLURALSIGHT Clone/IMAGES/one.png
  PLURALSIGHT Clone/IMAGES/party.png
  PLURALSIGHT Clone/IMAGES/ps-icon.png
  PLURALSIGHT Clone/IMAGES/python-7be70baaac.png
  PLURALSIGHT Clone/IMAGES/sandboxes.png
  PLURALSIGHT Clone/IMAGES/skills grid.jpg
  PLURALSIGHT Clone/IMAGES/twitter_PNG9.png
  PLURALSIGHT Clone/IMAGES/typing on laptop.png
  PLURALSIGHT Clone/IMAGES/vm.png
  PLURALSIGHT Clone/IMAGES/vmware.png
  PLURALSIGHT Clone/index.html
  PLURALSIGHT Clone/readme.md
  PLURALSIGHT Clone/scripts/index.js
  PLURALSIGHT Clone/styles/index.css
Labels: Level 2, GSSoC 22

#155 Cards updated
  assets/inshorts.jpg
  assets/quora.png
  index.css
  index.html
Labels: GSSoC 22

#170 Add scroll to top button on main website
  assets/arrow.png
  index.css
  index.html
Labels: enhancement, Level 1, GSSoC 22

#179 Candy Crush files added
  Candy_Crush_Clone/candy-crush-background.png
  Candy_Crush_Clone/images/blue-candy.png
  Candy_Crush_Clone/images/green-candy.png
  Candy_Crush_Clone/images/orange-candy.png
  Candy_Crush_Clone/images/purple-candy.png
  Candy_Crush_Clone/images/red-candy.png
  Candy_Crush_Clone/images/yellow-candy.png
  Candy_Crush_Clone/index.html
  Candy_Crush_Clone/script.js
  Candy_Crush_Clone/styles.css
  assets/candy-crush.png
  index.css
  index.html
Labels: GSSoC22, Level 1

#180 Added : Tesla Landing page Clone
  README.md
  Tesla/Output - SS/1.png
  Tesla/Output - SS/2.png
  Tesla/Output - SS/3.png
  Tesla/Output - SS/4.png
  Tesla/Output - SS/5.png
  Tesla/Output - SS/6.png
  Tesla/Output - SS/7.png
  Tesla/Output - SS/8.png
  Tesla/Readme.md
  Tesla/assests/Accessories.jpg
  Tesla/assests/Solar-Roof.jpg
  Tesla/assests/SolarPanels.jpg
  Tesla/assests/close-icon.png
  Tesla/assests/model-3.jpg
  Tesla/assests/model-S.jpg
  Tesla/assests/model-X.jpg
  Tesla/assests/model-Y.jpg
  Tesla/assests/tesla-logo.svg
  Tesla/index.html
  Tesla/script.js
  Tesla/style-1.css
  Tesla/style-2.css
Labels: Level 1

#201 Airbnb WebPage clone
  Airbnb WebPage Clone/images/Airbnb_Logo.svg
  Airbnb WebPage Clone/images/aisha.jpeg
  Airbnb WebPage Clone/images/ben.jpeg
  Airbnb WebPage Clone/images/couple.jpg
  Airbnb WebPage Clone/images/david.jpeg
  Airbnb WebPage Clone/images/header.png
  Airbnb WebPage Clone/images/joana.jpg
  Airbnb WebPage Clone/images/justin.jpg
  Airbnb WebPage Clone/images/kate.jpeg
  Airbnb WebPage Clone/images/logo-1.png
  Airbnb WebPage Clone/images/logo.png
  Airbnb WebPage Clone/images/mathew.jpeg
  Airbnb WebPage Clone/images/paul.jpeg
  Airbnb WebPage Clone/images/petz.jpeg
  Airbnb WebPage Clone/images/ricardo.jpg
  Airbnb WebPage Clone/images/rory.jpeg
  Airbnb WebPage Clone/images/tye.jpeg
  Airbnb WebPage Clone/index.html
  Airbnb WebPage Clone/readme.md
  Airbnb WebPage Clone/show.html
  Airbnb WebPage Clone/slick.js
  Airbnb WebPage Clone/styles.css
Labels: Level1, GSSoC22

#203 fix: improve accessibility by updating html tags
  index.html
Labels: fixed

#204 Zomato Clone Added
  Zomato_Homepage_Clone/.gitignore
  Zomato_Homepage_Clone/README.md
  Zomato_Homepage_Clone/package-lock.json
  Zomato_Homepage_Clone/package.json
  Zomato_Homepage_Clone/public/favicon.ico
  Zomato_Homepage_Clone/public/index.html
  Zomato_Homepage_Clone/public/logo192.png
  Zomato_Homepage_Clone/public/logo512.png
  Zomato_Homepage_Clone/public/manifest.json
  Zomato_Homepage_Clone/public/robots.txt
  Zomato_Homepage_Clone/src/App.js
  Zomato_Homepage_Clone/src/Data/restaurant.js
  Zomato_Homepage_Clone/src/components/common/Delivery/Delivery.css
  Zomato_Homepage_Clone/src/components/common/Delivery/Top-Brands/TopBrand-lists/index.js
  Zomato_Homepage_Clone/src/components/common/Delivery/Top-Brands/TopBrand-lists/topBrands-list.css
  Zomato_Homepage_Clone/src/components/common/Delivery/Top-Brands/TopBrands.css
  Zomato_Homepage_Clone/src/components/common/Delivery/Top-Brands/index.js
  Zomato_Homepage_Clone/src/components/common/Delivery/deliveryCollections/delivery-items/delivery-item.css
  Zomato_Homepage_Clone/src/components/common/Delivery/deliveryCollections/delivery-items/index.js
  Zomato_Homepage_Clone/src/components/common/Delivery/deliveryCollections/deliveryCollection.css
  Zomato_Homepage_Clone/src/components/common/Delivery/deliveryCollections/index.js
  Zomato_Homepage_Clone/src/components/common/Delivery/index.js
  Zomato_Homepage_Clone/src/components/common/DiningOut/dining.js
  Zomato_Homepage_Clone/src/components/common/DiningOut/diningOut.css
  Zomato_Homepage_Clone/src/components/common/DiningOut/index.js
  Zomato_Homepage_Clone/src/components/common/ExploreSection/ExploreCard/ExploreCard.css
  Zomato_Homepage_Clone/src/components/common/ExploreSection/ExploreCard/index.js
  Zomato_Homepage_Clone/src/components/common/ExploreSection/ExploreSection.css
  Zomato_Homepage_Clone/src/components/common/ExploreSection/index.js
  Zomato_Homepage_Clone/src/components/common/Footer/index.js
  Zomato_Homepage_Clone/src/components/common/Header/Header.css
  Zomato_Homepage_Clone/src/components/common/Header/index.js
  Zomato_Homepage_Clone/src/components/common/NightLife/Nightlife.css
  Zomato_Homepage_Clone/src/components/common/NightLife/index.js
  Zomato_Homepage_Clone/src/components/common/TabOptions/index.js
  Zomato_Homepage_Clone/src/components/common/TabOptions/tab.css
  Zomato_Homepage_Clone/src/components/common/carousel/NextArrow.js
  Zomato_Homepage_Clone/src/components/common/carousel/prevArrows.js
  Zomato_Homepage_Clone/src/components/common/collection/collection.css
  Zomato_Homepage_Clone/src/components/common/collection/index.js
  Zomato_Homepage_Clone/src/components/common/filters/filteritem/filteritem.css
  Zomato_Homepage_Clone/src/components/common/filters/filteritem/index.js
  Zomato_Homepage_Clone/src/components/common/filters/filters.css
  Zomato_Homepage_Clone/src/components/common/filters/index.js
  Zomato_Homepage_Clone/src/index.css
  Zomato_Homepage_Clone/src/index.js
  Zomato_Homepage_Clone/src/pages/home/index.js
  Zomato_Homepage_Clone/src/reportWebVitals.js
  Zomato_Homepage_Clone/src/setupTests.js
  Zomato_Homepage_Clone/src/styles/commonstyles.css
  Zomato_Homepage_Clone/src/styles/variable.css
Labels: GSSoC22

#206 #184 NYKAA Clone created
  NYKAA-CLONE/Myorder.html
  NYKAA-CLONE/Myprofile.html
  NYKAA-CLONE/Mywish.html
  NYKAA-CLONE/ProductDetail.html
  NYKAA-CLONE/ProductNykaaCosmetics.html
  NYKAA-CLONE/README.md
  NYKAA-CLONE/Signin.html
  NYKAA-CLONE/address.html
  NYKAA-CLONE/backend/db.json
  NYKAA-CLONE/backend/package-lock.json
  NYKAA-CLONE/backend/package.json
  NYKAA-CLONE/backend/server.js
  NYKAA-CLONE/component/chatboxx.js
  NYKAA-CLONE/component/navbar.js
  NYKAA-CLONE/component/pagefooter.js
  NYKAA-CLONE/foot.html
  NYKAA-CLONE/images/icons.html
  NYKAA-CLONE/index.html
  NYKAA-CLONE/landingpage.html
  NYKAA-CLONE/nykaa.html
  NYKAA-CLONE/offer.html
  NYKAA-CLONE/payment.html
  NYKAA-CLONE/register_nykaa.html
  NYKAA-CLONE/scripts/Myorder.js
  NYKAA-CLONE/scripts/Myprofile.js
  NYKAA-CLONE/scripts/Mywish.js
  NYKAA-CLONE/scripts/ProductNykaaCosmetics.css
  NYKAA-CLONE/scripts/ProductNykaaCosmetics.js
  NYKAA-CLONE/scripts/ShowChatBox.js
  NYKAA-CLONE/scripts/address.js
  NYKAA-CLONE/scripts/chatbox.js
  NYKAA-CLONE/scripts/index.js
  NYKAA-CLONE/scripts/landipage.js
  NYKAA-CLONE/scripts/offer.js
  NYKAA-CLONE/scripts/payment.js
  NYKAA-CLONE/scripts/productDetail.js
  NYKAA-CLONE/scripts/signin.js
  NYKAA-CLONE/scripts/sucess.js
  NYKAA-CLONE/styles/Help.css
  NYKAA-CLONE/styles/Myorder.css
  NYKAA-CLONE/styles/Myprofile.css
  NYKAA-CLONE/styles/Mywish.css
  NYKAA-CLONE/styles/ProductNykaaCosmetics.css
  NYKAA-CLONE/styles/address.css
  NYKAA-CLONE/styles/chatbox.css
  NYKAA-CLONE/styles/footer.css
  NYKAA-CLONE/styles/getapp.css
  NYKAA-CLONE/styles/index.css
  NYKAA-CLONE/styles/landingpage.css
  NYKAA-CLONE/styles/offer.css
  NYKAA-CLONE/styles/payment.css
  NYKAA-CLONE/styles/productDetail.css
  NYKAA-CLONE/styles/signin.css
  NYKAA-CLONE/styles/style.css
  NYKAA-CLONE/styles/sucess.css
  NYKAA-CLONE/sucess.html
  README.md
  assets/nykaa.jpg
  index.css
  index.html
Labels: Level1, GSSoC22

#211 Revert "#184 NYKAA Clone created"
  NYKAA-CLONE/Myorder.html
  NYKAA-CLONE/Myprofile.html
  NYKAA-CLONE/Mywish.html
  NYKAA-CLONE/ProductDetail.html
  NYKAA-CLONE/ProductNykaaCosmetics.html
  NYKAA-CLONE/README.md
  NYKAA-CLONE/Signin.html
  NYKAA-CLONE/address.html
  NYKAA-CLONE/backend/db.json
  NYKAA-CLONE/backend/package-lock.json
  NYKAA-CLONE/backend/package.json
  NYKAA-CLONE/backend/server.js
  NYKAA-CLONE/component/chatboxx.js
  NYKAA-CLONE/component/navbar.js
  NYKAA-CLONE/component/pagefooter.js
  NYKAA-CLONE/foot.html
  NYKAA-CLONE/images/icons.html
  NYKAA-CLONE/index.html
  NYKAA-CLONE/landingpage.html
  NYKAA-CLONE/nykaa.html
  NYKAA-CLONE/offer.html
  NYKAA-CLONE/payment.html
  NYKAA-CLONE/register_nykaa.html
  NYKAA-CLONE/scripts/Myorder.js
  NYKAA-CLONE/scripts/Myprofile.js
  NYKAA-CLONE/scripts/Mywish.js
  NYKAA-CLONE/scripts/ProductNykaaCosmetics.css
  NYKAA-CLONE/scripts/ProductNykaaCosmetics.js
  NYKAA-CLONE/scripts/ShowChatBox.js
  NYKAA-CLONE/scripts/address.js
  NYKAA-CLONE/scripts/chatbox.js
  NYKAA-CLONE/scripts/index.js
  NYKAA-CLONE/scripts/landipage.js
  NYKAA-CLONE/scripts/offer.js
  NYKAA-CLONE/scripts/payment.js
  NYKAA-CLONE/scripts/productDetail.js
  NYKAA-CLONE/scripts/signin.js
  NYKAA-CLONE/scripts/sucess.js
  NYKAA-CLONE/styles/Help.css
  NYKAA-CLONE/styles/Myorder.css
  NYKAA-CLONE/styles/Myprofile.css
  NYKAA-CLONE/styles/Mywish.css
  NYKAA-CLONE/styles/ProductNykaaCosmetics.css
  NYKAA-CLONE/styles/address.css
  NYKAA-CLONE/styles/chatbox.css
  NYKAA-CLONE/styles/footer.css
  NYKAA-CLONE/styles/getapp.css
  NYKAA-CLONE/styles/index.css
  NYKAA-CLONE/styles/landingpage.css
  NYKAA-CLONE/styles/offer.css
  NYKAA-CLONE/styles/payment.css
  NYKAA-CLONE/styles/productDetail.css
  NYKAA-CLONE/styles/signin.css
  NYKAA-CLONE/styles/style.css
  NYKAA-CLONE/styles/sucess.css
  NYKAA-CLONE/sucess.html
  README.md
  assets/nykaa.jpg
  index.css
  index.html
Labels: GSSoC22

#217 Airbnb Added in site
  FAQ-PAGE/faq.html
  assets/airbnb.png
  index.css
  index.html
Labels: GSSoC22

#218 Mac OS Clone
  Mac OS Clone/css/style.css
  Mac OS Clone/img/bg/panorama-3629120.jpg
  Mac OS Clone/img/firefox.svg
  Mac OS Clone/img/google-chrome.svg
  Mac OS Clone/img/photoflare.svg
  Mac OS Clone/img/preferences-desktop-icons.svg
  Mac OS Clone/img/preferences-desktop-plasma.svg
  Mac OS Clone/img/softwarecenter.svg
  Mac OS Clone/img/spotify-client.svg
  Mac OS Clone/img/sublime-text.svg
  Mac OS Clone/img/visual-studio-code.svg
  Mac OS Clone/index.html
  Mac OS Clone/readme.md
Labels: Level1, GSSoC22

#219 deleted airbnb
  Airbnb WebPage Clone/images/Airbnb_Logo.svg
  Airbnb WebPage Clone/images/aisha.jpeg
  Airbnb WebPage Clone/images/ben.jpeg
  Airbnb WebPage Clone/images/couple.jpg
  Airbnb WebPage Clone/images/david.jpeg
  Airbnb WebPage Clone/images/header.png
  Airbnb WebPage Clone/images/joana.jpg
  Airbnb WebPage Clone/images/justin.jpg
  Airbnb WebPage Clone/images/kate.jpeg
  Airbnb WebPage Clone/images/logo-1.png
  Airbnb WebPage Clone/images/logo.png
  Airbnb WebPage Clone/images/mathew.jpeg
  Airbnb WebPage Clone/images/paul.jpeg
  Airbnb WebPage Clone/images/petz.jpeg
  Airbnb WebPage Clone/images/ricardo.jpg
  Airbnb WebPage Clone/images/rory.jpeg
  Airbnb WebPage Clone/images/tye.jpeg
  Airbnb WebPage Clone/index.html
  Airbnb WebPage Clone/readme.md
  Airbnb WebPage Clone/show.html
  Airbnb WebPage Clone/slick.js
  Airbnb WebPage Clone/styles.css
Labels: GSSoC22

#220 Airbnb WebPage clone
  AirBnb WebPage Clone/images/Airbnb_Logo.svg
  AirBnb WebPage Clone/images/aisha.jpeg
  AirBnb WebPage Clone/images/ben.jpeg
  AirBnb WebPage Clone/images/couple.jpg
  AirBnb WebPage Clone/images/david.jpeg
  AirBnb WebPage Clone/images/header.png
  AirBnb WebPage Clone/images/joana.jpg
  AirBnb WebPage Clone/images/justin.jpg
  AirBnb WebPage Clone/images/kate.jpeg
  AirBnb WebPage Clone/images/logo-1.png
  AirBnb WebPage Clone/images/logo.png
  AirBnb WebPage Clone/images/mathew.jpeg
  AirBnb WebPage Clone/images/paul.jpeg
  AirBnb WebPage Clone/images/petz.jpeg
  AirBnb WebPage Clone/images/ricardo.jpg
  AirBnb WebPage Clone/images/rory.jpeg
  AirBnb WebPage Clone/images/tye.jpeg
  AirBnb WebPage Clone/index.html
  AirBnb WebPage Clone/readme.md
  AirBnb WebPage Clone/script.js
  AirBnb WebPage Clone/styles.css
Labels: Level1, GSSoC22

#223 Added microsoft teams page clone files
  Microsoft_Teams_Page_Clone/assets/css/bootstrap.css
  Microsoft_Teams_Page_Clone/assets/css/bootstrap.css.map
  Microsoft_Teams_Page_Clone/assets/css/style.css
  Microsoft_Teams_Page_Clone/assets/media/Teams_Icon.jpg
  Microsoft_Teams_Page_Clone/assets/media/person.png
  Microsoft_Teams_Page_Clone/index.html
  Microsoft_Teams_Page_Clone/scripts/bootstrap.bundle.js
  Microsoft_Teams_Page_Clone/scripts/bootstrap.bundle.js.map
  README.md
Labels: Level1, GSSoC22
