Repository Rayman-Sodhi/Clone-IT, pull requests merged in 2022-08, with the labels that each got.

#701 SB UI KIT PRO Lead-Capture
  README.md
  SB UI KIT PRO/Css/style.css
  SB UI KIT PRO/Home.html
  SB UI KIT PRO/Images/dribble1.png
  SB UI KIT PRO/Images/google.png
  SB UI KIT PRO/Images/instagram.svg
  SB UI KIT PRO/Images/mail_chimp.svg
  SB UI KIT PRO/JS/SB_UI.js
Labels: HSOC22-Level-3, HSOC22

#700 Adding Google Pay Clone
  Google Pay Clone/Readme.md
  Google Pay Clone/img/grofers.jpg
  Google Pay Clone/img/logo.png
  Google Pay Clone/img/logo512.png
  Google Pay Clone/img/oyo.png
  Google Pay Clone/img/profile.jpg
  Google Pay Clone/index.html
  Google Pay Clone/sass/main.scss
  Google Pay Clone/script.js
  Google Pay Clone/style.css
Labels: HSOC22-Level-2, HSOC22

#703 Cartoon network Clone
  Cartoon Network/Cartoonnetwork.html
  Cartoon Network/Images/CartoonNetworklogo.jpg
  Cartoon Network/Images/Ytv.png
  Cartoon Network/Images/adventure-time.png
  Cartoon Network/Images/apple-onion.png
  Cartoon Network/Images/bare-bear.png
  Cartoon Network/Images/ben-10.png
  Cartoon Network/Images/cn-logo.png
  Cartoon Network/Images/corus-logo.png
  Cartoon Network/Images/corus.jpeg
  Cartoon Network/Images/disney-junior.png
  Cartoon Network/Images/disney-logo.png
  Cartoon Network/Images/gumball.png
  Cartoon Network/Images/heroes.png
  Cartoon Network/Images/junior.png
  Cartoon Network/Images/logodisney.png
  Cartoon Network/Images/looney-tunes.png
  Cartoon Network/Images/mao.png
  Cartoon Network/Images/powerpuff.png
  Cartoon Network/Images/regular-show.png
  Cartoon Network/Images/steven-universe.png
  Cartoon Network/Images/teletoon-logo.png
  Cartoon Network/Images/toon.png
  Cartoon Network/Images/treehouse(1).png
  Cartoon Network/Images/treehouse.png
  Cartoon Network/Images/ytvc.jpeg
  Cartoon Network/main.css
  README.md
Labels: HSOC22-Level-2, HSOC22

#705 Adding Twitter Clone and Two Login Forms Clone
  Twitter Clone/assets/images/post1.jpg
  Twitter Clone/assets/images/post2.jpg
  Twitter Clone/assets/images/post3.jpeg
  Twitter Clone/assets/images/profile.png
  Twitter Clone/first-login-assets/banner.jpg
  Twitter Clone/first-login-assets/twitter.png
  Twitter Clone/first_login.css
  Twitter Clone/first_login.html
  Twitter Clone/index.html
  Twitter Clone/second-login-assets/app-store.png
  Twitter Clone/second-login-assets/google-play.png
  Twitter Clone/second-login-assets/logo.jpg
  Twitter Clone/second_login.css
  Twitter Clone/second_login.html
  Twitter Clone/style.css
Labels: HSOC22
