Repository Rayman-Sodhi/Clone-IT, pull requests merged in 2022-05, with the labels that each got.

#425 Added Google Maps Clone
  Google Maps Clone/Readme.md
  Google Maps Clone/index.html
  Google Maps Clone/script.js
  Google Maps Clone/style.css
Labels: GSSoC22, Level3

#430 adding images to zara clone
  zara/index.html
Labels: Level1, GSSoC22

#431 Made website changes
  index.css
  index.html
Labels: Level2, GSSoC22

#433 Plantix Clone
  Plantix Clone/images/bgfixed.jpg
  Plantix Clone/images/crop-1.jpg
  Plantix Clone/images/crop-2.jpg
  Plantix Clone/images/crop-3.jpg
  Plantix Clone/images/crop-4.jpg
  Plantix Clone/images/first.jpg
  Plantix Clone/images/google.png
  Plantix Clone/images/green1.jpg
  Plantix Clone/images/green2.png
  Plantix Clone/images/green3.jpg
  Plantix Clone/images/green4.jpg
  Plantix Clone/images/green5.jpg
  Plantix Clone/images/image1.jpg
  Plantix Clone/images/image2.png
  Plantix Clone/images/image3.png
  Plantix Clone/images/img-1.jpg
  Plantix Clone/images/img-2.jpg
  Plantix Clone/images/img-3.jpg
  Plantix Clone/images/img-4.jpg
  Plantix Clone/images/mobile.png
  Plantix Clone/images/mobile2.png
  Plantix Clone/images/mobile3.png
  Plantix Clone/images/phone.png
  Plantix Clone/images/plantix-logo.png
  Plantix Clone/images/press1.jpg
  Plantix Clone/images/press2.jpg
  Plantix Clone/images/press3.jpg
  Plantix Clone/images/press4.jpg
  Plantix Clone/images/press5.jpg
  Plantix Clone/images/press6.jpg
  Plantix Clone/images/press7.jpg
  Plantix Clone/images/press8.jpg
  Plantix Clone/images/press9.jpg
  Plantix Clone/images/tomake.jpg
  Plantix Clone/images/tomake1.jpg
  Plantix Clone/index.html
  Plantix Clone/styles.css
Labels: Level2, GSSoC22

#437 CNN clone
  INDEX~1.HTM
  css/bootstrap-grid.min.css
  css/fontawesome-all.min.css
  css/style.css
  img/articles/article-1.jpg
  img/articles/article-10.jpg
  img/articles/article-11.jpg
  img/articles/article-12.jpg
  img/articles/article-13.jpg
  img/articles/article-14.jpg
  img/articles/article-15.jpg
  img/articles/article-16.jpg
  img/articles/article-17.jpg
  img/articles/article-18.jpg
  img/articles/article-19.jpg
  img/articles/article-2.jpg
  img/articles/article-20.jpg
  img/articles/article-21.jpg
  img/articles/article-22.jpg
  img/articles/article-23.jpg
  img/articles/article-24.jpg
  img/articles/article-25.jpg
  img/articles/article-26.jpg
  img/articles/article-27.jpg
  img/articles/article-28.jpg
  img/articles/article-29.jpg
  img/articles/article-3.jpg
  img/articles/article-4.jpg
  img/articles/article-5.jpg
  img/articles/article-6.jpg
  img/articles/article-7.jpg
  img/articles/article-8.jpg
  img/articles/article-9.jpg
  img/logo-ar.png
  img/logo-esp.png
  img/logo-us.png
  img/logo_cnn.png
  img/weather-icon.png
  webfonts/fa-brands-400.eot
  webfonts/fa-brands-400.svg
  webfonts/fa-brands-400.ttf
  webfonts/fa-brands-400.woff
  webfonts/fa-brands-400.woff2
  webfonts/fa-regular-400.eot
  webfonts/fa-regular-400.svg
  webfonts/fa-regular-400.ttf
  webfonts/fa-regular-400.woff
  webfonts/fa-regular-400.woff2
  webfonts/fa-solid-900.eot
  webfonts/fa-solid-900.svg
  webfonts/fa-solid-900.ttf
  webfonts/fa-solid-900.woff
  webfonts/fa-solid-900.woff2
Labels: Level2, GSSoC22

#440 Wordle description changed
  index.html
Labels: Level1, GSSoC22

#434 Weather
  Weather-CLONE/index.html
  Weather-CLONE/script.css
  Weather-CLONE/script.js
  index.css
  index.html
Labels: Level2, GSSoC22

#442 Changed footer in hulu
  hulu-webpage-clone/css/style.css
  hulu-webpage-clone/img/about ads.png
  hulu-webpage-clone/index.html
Labels: Level2, GSSoC22

#443 added zerodha clone
  Zerodha Clone/.vscode/settings.json
  Zerodha Clone/img/arrow-right-solid.svg
  Zerodha Clone/img/ecosystem.png
  Zerodha Clone/img/index-education.svg
  Zerodha Clone/img/landing1.png
  Zerodha Clone/img/largest-broker.svg
  Zerodha Clone/img/logo.svg
  Zerodha Clone/img/press-logos.png
  Zerodha Clone/img/social-img/facebook-square-brands.svg
  Zerodha Clone/img/social-img/instagram-brands.svg
  Zerodha Clone/img/social-img/linkedin-in-brands.svg
  Zerodha Clone/img/social-img/telegram-brands.svg
  Zerodha Clone/img/social-img/twitter-brands.svg
  Zerodha Clone/index2.html
  Zerodha Clone/style2.css
Labels: Level1, GSSoC22

#459 Added responsiveness to NVIDIA clone
  NVIDIA_Clone/README.md
  NVIDIA_Clone/index.html
  NVIDIA_Clone/styles.css
Labels: enhancement, Level1, GSSoC22

#448 Uber Payment page Clone
  Uber Payment Page Clone/index.html
  Uber Payment Page Clone/preview.jpg
  Uber Payment Page Clone/style.css
Labels: Level1, GSSoC22

#450 Tesla Car
  Tesla Car/index.html
  Tesla Car/style.css
Labels: Level1, GSSoC22

#470 Added HP Laptop Clone
  HP Laptop Clone/images/OMEN-logo3.png
  HP Laptop Clone/images/icons8-india-16.png
  HP Laptop Clone/images/icons8-search.svg
  HP Laptop Clone/images/logo-hp.png
  HP Laptop Clone/images/printers/HP-Laserjet-Managed-Flow-MFP-E82550z.webp
  HP Laptop Clone/images/printers/HP-NS-Laser-MFP-1200-thumb.webp
  HP Laptop Clone/images/printers/HPInkTank410.webp
  HP Laptop Clone/images/printers/HPSmartTank515.webp
  HP Laptop Clone/images/printers/LaserJetPro_m404dn.webp
  HP Laptop Clone/images/printers/graph-solutions_thumb.webp
  HP Laptop Clone/images/z-by-hp-new.png
  HP Laptop Clone/index.html
  HP Laptop Clone/style.css
Labels: Level1, GSSoC22

#452 Car dealer ship website "costal saves" clone
  Car Dealership Costal Saves Clone/index.html
  Car Dealership Costal Saves Clone/style.css
Labels: Level1, GSSoC22

#464 Excel Clone recommit
  ExcelClone/1.js
  ExcelClone/2.js
  ExcelClone/Demo.png
  ExcelClone/index.html
  ExcelClone/readme.md
  ExcelClone/script.js
  ExcelClone/style.css
Labels: Level1, GSSoC22

#461 Dog Website
  Urban Collar Dog Website Clone/index.html
  Urban Collar Dog Website Clone/script.js
  Urban Collar Dog Website Clone/style.css
Labels: Level2, GSSoC22

#474 GYM Website
  gym website/huu.jpg
  gym website/img.jpg.jpg
  gym website/index.html
Labels: Level2, GSSoC22

#476 Added Office page in Microsoft Clone
  Microsoft-Clone/assets/Business.webp
  Microsoft-Clone/assets/Education.webp
  Microsoft-Clone/assets/Enterprise.webp
  Microsoft-Clone/assets/For business.webp
  Microsoft-Clone/assets/For enterprise.jpg
  Microsoft-Clone/assets/For home.webp
  Microsoft-Clone/assets/Home.webp
  Microsoft-Clone/assets/Teams.webp
  Microsoft-Clone/assets/excel.webp
  Microsoft-Clone/assets/office-1.webp
  Microsoft-Clone/assets/outlook.webp
  Microsoft-Clone/assets/powerpoint.webp
  Microsoft-Clone/assets/word.webp
  Microsoft-Clone/index.html
  Microsoft-Clone/office.html
  Microsoft-Clone/styles/office.css
  Microsoft-Clone/styles/style.css
  Sphere Online Judge Clone/images/A.png
  Sphere Online Judge Clone/images/Brain-wars
  Sphere Online Judge Clone/images/D-1.png
  Sphere Online Judge Clone/images/D-2.png
  Sphere Online Judge Clone/images/D.png
  Sphere Online Judge Clone/images/H.png
  Sphere Online Judge Clone/images/K.png
  Sphere Online Judge Clone/images/M.png
  Sphere Online Judge Clone/images/O-1.png
  Sphere Online Judge Clone/images/O.png
  Sphere Online Judge Clone/images/R.png
  Sphere Online Judge Clone/images/RSS.gif
  Sphere Online Judge Clone/images/S.png
  Sphere Online Judge Clone/images/W.png
  Sphere Online Judge Clone/images/icon.jpeg
  Sphere Online Judge Clone/images/img-1
  Sphere Online Judge Clone/images/img-2
  Sphere Online Judge Clone/images/img-3
  Sphere Online Judge Clone/images/img-4
  Sphere Online Judge Clone/images/img-5
  Sphere Online Judge Clone/images/img-6
  Sphere Online Judge Clone/images/logo.png
  Sphere Online Judge Clone/images/user.png
  Sphere Online Judge Clone/index.html
  Sphere Online Judge Clone/style.css
Labels: Level1, GSSoC22

#482 Added About, signup & product in Zerodha Clone
  Zerodha Clone/About.html
  Zerodha Clone/css/About.css
  Zerodha Clone/css/products.css
  Zerodha Clone/css/signup.css
  Zerodha Clone/css/style.css
  Zerodha Clone/img/API.png
  Zerodha Clone/img/Appstore.svg
  Zerodha Clone/img/CCO.jpg
  Zerodha Clone/img/CFO.jpg
  Zerodha Clone/img/COO.jpg
  Zerodha Clone/img/CQO.jpg
  Zerodha Clone/img/CTO.jpg
  Zerodha Clone/img/Education.jpg
  Zerodha Clone/img/Stragey.jpg
  Zerodha Clone/img/Streak.png
  Zerodha Clone/img/bull.svg
  Zerodha Clone/img/ceo.jpg
  Zerodha Clone/img/coim.png
  Zerodha Clone/img/console.png
  Zerodha Clone/img/ditto.png
  Zerodha Clone/img/goldenpi.png
  Zerodha Clone/img/googlepay.svg
  Zerodha Clone/img/kite.png
  Zerodha Clone/img/signup.png
  Zerodha Clone/img/smallcase.png
  Zerodha Clone/img/varsity.png
  Zerodha Clone/index.html
  Zerodha Clone/products.html
  Zerodha Clone/signup.html
Labels: Level2, GSSoC22

#488 Added Vespa Clone
  Vespa Clone/img/Flag of India.webp
  Vespa Clone/img/arrow-gamma-dx.webp
  Vespa Clone/img/arrow-gamma-sx.webp
  Vespa Clone/img/banner_shoponline.webp
  Vespa Clone/img/bg-social-home.png
  Vespa Clone/img/bikes/SXL-frontale.webp
  Vespa Clone/img/bikes/VXL-frontale.webp
  Vespa Clone/img/bikes/ZX-frontale.webp
  Vespa Clone/img/bikes/elegante-frontale.webp
  Vespa Clone/img/bikes/notte-frontale.webp
  Vespa Clone/img/bikes/urban-club-frontale.webp
  Vespa Clone/img/clothing & accessories.jpg
  Vespa Clone/img/fb.svg
  Vespa Clone/img/icon-menu.svg
  Vespa Clone/img/ig.svg
  Vespa Clone/img/logo-footer.webp
  Vespa Clone/img/logo.svg
  Vespa Clone/img/tw.svg
  Vespa Clone/img/vespa-for-children.webp
  Vespa Clone/img/vespa_heritage.webp
  Vespa Clone/img/vespaindia.webp
  Vespa Clone/img/wide-footer.webp
  Vespa Clone/img/yt.svg
  Vespa Clone/index.html
  Vespa Clone/style.css
Labels: Level2, GSSoC22

#487 Apk Mirror
  APK Mirror/index.html
  APK Mirror/style.css
Labels: Level1, GSSoC22

#481 Update README.md, add all projects
  README.md
Labels: Level1, GSSoC22

#484 Cartoon Network
  Cartoon Network/index.html
  Cartoon Network/style.css
Labels: Level1, GSSoC22

#485 DC
  DC Comic/index.html
  DC Comic/style.css
Labels: Level1, GSSoC22

#497 EA Sports Facebook Page Clone
  EA Sports Facebook Page/index.html
  EA Sports Facebook Page/style.css
Labels: GSSoC22

#510 BBC News
  BBC News/images/bbc-logo.png
  BBC News/images/bell-icon.png
  BBC News/images/clock-icon.png
  BBC News/images/down-arrow-icon.png
  BBC News/images/local-news-pin-icon.png
  BBC News/images/search-icon.png
  BBC News/images/sign-in-icon.png
  BBC News/images/top-story.png
  BBC News/images/video-thumbnail-1.png
  BBC News/images/video-thumbnail-2.PNG
  BBC News/images/video-thumbnail-3.PNG
  BBC News/images/video-thumbnail-4.PNG
  BBC News/index.html
  BBC News/style.css
  BBC News/style1.css
Labels: Level1, GSSoC22

#512 Adidas
  Adidas Clone/index.html
  Adidas Clone/script/index.js
  Adidas Clone/script/switch.js
  Adidas Clone/script/w2.js
  Adidas Clone/script/wl1.js
  Adidas Clone/styles/hf1.css
  Adidas Clone/styles/home.css
  Adidas Clone/styles/index.css
  Adidas Clone/styles/w2.css
  Adidas Clone/styles/wl1.css
  Adidas Clone/w2.html
  Adidas Clone/wl1.html
Labels: Level2, GSSoC22

#508 Added Tata Motors Clone
  Tata Motors Clone/img/b-0.jpg
  Tata Motors Clone/img/b-2.jpg
  Tata Motors Clone/img/b-3.jpg
  Tata Motors Clone/img/blog-1.jpg
  Tata Motors Clone/img/blog-2.jpg
  Tata Motors Clone/img/blog-3.jpg
  Tata Motors Clone/img/corporate-presentation-fy21.jpg
  Tata Motors Clone/img/dots-bg.png
  Tata Motors Clone/img/home-hp-banner-web.jpg
  Tata Motors Clone/img/home-safari-banner-17jan22-web.jpg
  Tata Motors Clone/img/icons8-search-32.png
  Tata Motors Clone/img/profile_info.jpg
  Tata Motors Clone/img/punch-banner-04oct21-web.jpg
  Tata Motors Clone/img/radio-active-img.png
  Tata Motors Clone/img/radio-inactive-img.png
  Tata Motors Clone/img/slider1.jpg
  Tata Motors Clone/img/slider2.jpg
  Tata Motors Clone/img/slider4.jpg
  Tata Motors Clone/img/sm-background.gif
  Tata Motors Clone/img/sprite.png
  Tata Motors Clone/img/tata_logo.png
  Tata Motors Clone/img/tata_motors_journey.gif
  Tata Motors Clone/img/tata_motors_logo.png
  Tata Motors Clone/img/video.jpg
  Tata Motors Clone/img/world_map.gif
  Tata Motors Clone/index.html
  Tata Motors Clone/style.css
Labels: Level2, GSSoC22

#518 Added Goldman Sachs Clone
  Goldman Sach Clone/img/545705.png
  Goldman Sach Clone/img/blue-background-d.webp
  Goldman Sach Clone/img/careers-sidekick-1400x1300.webp
  Goldman Sach Clone/img/careers-sidekick-inset.webp
  Goldman Sach Clone/img/corporations-institutions.webp
  Goldman Sach Clone/img/de-globalization-528x528-600x600.webp
  Goldman Sach Clone/img/download (1).png
  Goldman Sach Clone/img/hero-img.jpg
  Goldman Sach Clone/img/hero-inset (1).webp
  Goldman Sach Clone/img/hero-inset.webp
  Goldman Sach Clone/img/individuals.webp
  Goldman Sach Clone/img/logo.svg
  Goldman Sach Clone/img/patrick-cantlay-700x700.webp
  Goldman Sach Clone/img/recession.webp
  Goldman Sach Clone/img/search-icon.png
  Goldman Sach Clone/index.html
  Goldman Sach Clone/style.css
Labels: Level1, GSSoC22

#521 Google Classroom Clone
  google_classroom_clone/.gitignore
  google_classroom_clone/README.md
  google_classroom_clone/package-lock.json
  google_classroom_clone/package.json
  google_classroom_clone/public/index.html
  google_classroom_clone/public/manifest.json
  google_classroom_clone/public/robots.txt
  google_classroom_clone/src/App.css
  google_classroom_clone/src/App.js
  google_classroom_clone/src/components/Announcement.css
  google_classroom_clone/src/components/Announcement.js
  google_classroom_clone/src/components/ClassCard.css
  google_classroom_clone/src/components/ClassCard.js
  google_classroom_clone/src/components/CreateClass.js
  google_classroom_clone/src/components/JoinClass.js
  google_classroom_clone/src/components/Navbar.css
  google_classroom_clone/src/components/Navbar.js
  google_classroom_clone/src/firebase.js
  google_classroom_clone/src/index.css
  google_classroom_clone/src/index.js
  google_classroom_clone/src/reportWebVitals.js
  google_classroom_clone/src/screens/Class.css
  google_classroom_clone/src/screens/Class.js
  google_classroom_clone/src/screens/Dashboard.css
  google_classroom_clone/src/screens/Dashboard.js
  google_classroom_clone/src/screens/Home.css
  google_classroom_clone/src/screens/Home.js
  google_classroom_clone/src/setupTests.js
  google_classroom_clone/src/utils/atoms.js
Labels: Level2, GSSoC22

#523 tiktok
  TikTok Clone/README.md
  TikTok Clone/index.html
  TikTok Clone/iphone.png
  TikTok Clone/logo1.png
  TikTok Clone/preview.jpg
  TikTok Clone/song image.jpg
  TikTok Clone/style.css
  TikTok Clone/video1.mp4
Labels: Level1, GSSoC22

#525 ClearTax
  ClearTax Clone/index.html
  ClearTax Clone/preview.gif
  ClearTax Clone/preview1.jpg
  ClearTax Clone/readme.md
  ClearTax Clone/script.js
  ClearTax Clone/style.css
Labels: Level1, GSSoC22

#532 Updates on ZARA's new website
  zara/index.html
  zara/style.css
Labels: Level1, GSSoC22

#540 iPhone 13 Commercial Website Clone
  iPhone 13 clone/README.md
  iPhone 13 clone/index.html
  iPhone 13 clone/ip12.png
  iPhone 13 clone/script.js
  iPhone 13 clone/style.css
Labels: Level2, GSSoC22

#544 Khadim's Clone created
  Khadim's Clone/CSS/bootstrap.min.css
  Khadim's Clone/CSS/styles.css
  Khadim's Clone/FONT/Helvetica-Neus/Pragmatica-ExtraLight.woff
  Khadim's Clone/FONT/Helvetica-Neus/example.html
  Khadim's Clone/FONT/Helvetica-Neus/style.css
  Khadim's Clone/FONT/Nike-Futura/Futura Condensed Extra Bold Oblique.otf
  Khadim's Clone/FONT/Nike-Futura/readme.html
  Khadim's Clone/ICON/khadim-icon.png
  Khadim's Clone/IMG/Opera Snapshot_2022-05-21_173314_index.html.png
  Khadim's Clone/IMG/Opera Snapshot_2022-05-21_173326_index.html.png
  Khadim's Clone/IMG/Opera Snapshot_2022-05-21_173335_index.html.png
  Khadim's Clone/IMG/Opera Snapshot_2022-05-21_173345_index.html.png
  Khadim's Clone/IMG/Opera Snapshot_2022-05-21_173355_index.html.png
  Khadim's Clone/LICENSE
  Khadim's Clone/README.md
  Khadim's Clone/WEBP/9e80ffd5-e57b-498c-8443-582e89bdae33.webp
  Khadim's Clone/WEBP/KHADIM-BANNER1.webp
  Khadim's Clone/WEBP/KHADIM-BANNER2.webp
  Khadim's Clone/WEBP/khadim-logo.webp
  Khadim's Clone/WEBP/khadim-shop1.webp
  Khadim's Clone/WEBP/khadim-shop2.webp
  Khadim's Clone/WEBP/khadim-shop3.webp
  Khadim's Clone/WEBP/khadim_explore1.webp
  Khadim's Clone/WEBP/khadim_explore2.webp
  Khadim's Clone/WEBP/khadim_explore3.webp
  Khadim's Clone/WEBP/khadim_kid_new1.webp
  Khadim's Clone/WEBP/khadim_kid_new2.webp
  Khadim's Clone/WEBP/khadim_men_new1.webp
  Khadim's Clone/WEBP/khadim_men_new2.webp
  Khadim's Clone/WEBP/khadim_women_new1.webp
  Khadim's Clone/WEBP/khadim_women_new2.webp
  Khadim's Clone/WEBP/nike-website-banner-landscape.webp
  Khadim's Clone/WEBP/nike-website-banner-portrait.webp
  Khadim's Clone/WEBP/sandal-1.webp
  Khadim's Clone/WEBP/sandal-2.webp
  Khadim's Clone/WEBP/sandal-3.webp
  Khadim's Clone/WEBP/static-nike-banner-2.webp
  Khadim's Clone/WEBP/static-nike-banner.webp
  Khadim's Clone/index.html
Labels: GSSoC22

#548 Telegram WebApp Clone
  Telegram Clone/assets/css/style.css
  Telegram Clone/assets/images/placeholder/1.jpg
  Telegram Clone/assets/images/placeholder/10.jpg
  Telegram Clone/assets/images/placeholder/11.jpg
  Telegram Clone/assets/images/placeholder/2.jpg
  Telegram Clone/assets/images/placeholder/3.jpg
  Telegram Clone/assets/images/placeholder/4.jpg
  Telegram Clone/assets/images/placeholder/5.jpg
  Telegram Clone/assets/images/placeholder/6.jpg
  Telegram Clone/assets/images/placeholder/7.jpg
  Telegram Clone/assets/images/placeholder/8.jpg
  Telegram Clone/assets/images/placeholder/9.jpg
  Telegram Clone/assets/js/main.js
  Telegram Clone/assets/js/store.js
  Telegram Clone/index.html
  Telegram Clone/readme.md
Labels: GSSoC22, Level3

#542 Added Clubhouse clone
  Clubhouse Clone/img/appstore.6f955d329ad7.svg
  Clubhouse Clone/img/googleplay.a1b4ed6211c9.svg
  Clubhouse Clone/img/hero_.png
  Clubhouse Clone/img/img_app_icon_wws.1c1a80b353ce.png
  Clubhouse Clone/img/img_collisions.4f05b80b632a.png
  Clubhouse Clone/img/img_unlikely.a973b3546b1e.png
  Clubhouse Clone/img/instagram.png
  Clubhouse Clone/img/linkedin.png
  Clubhouse Clone/img/logo.2af78f862152.png
  Clubhouse Clone/img/phone_frame_lg.a6d0e08449b4.png
  Clubhouse Clone/img/qr_code_dark.abd8babca33e.png
  Clubhouse Clone/img/qr_code_light.5eed4efad9f3.png
  Clubhouse Clone/img/twitter.png
  Clubhouse Clone/index.html
  Clubhouse Clone/style.css
Labels: Level2, GSSoC22

#550 Rolex Clone
  Rolex clone/README.md
  Rolex clone/index.html
  Rolex clone/rolex-1.svg
  Rolex clone/script.js
  Rolex clone/style.css
Labels: GSSoC22, Level3

#560 Added Evernote Clone
  Evernote Clone/img/calendar_icon.svg
  Evernote Clone/img/checked.png
  Evernote Clone/img/company-logo/business-active.png
  Evernote Clone/img/company-logo/entrepreneur-magazine_active.png
  Evernote Clone/img/company-logo/forbes-active.png
  Evernote Clone/img/company-logo/logo-inc-active.png
  Evernote Clone/img/company-logo/the-verge_active.png
  Evernote Clone/img/company-logo/well-good_active.png
  Evernote Clone/img/doc-scanning.svg
  Evernote Clone/img/footer-logo.svg
  Evernote Clone/img/homepage-quote.svg
  Evernote Clone/img/navigate-desktop.svg
  Evernote Clone/img/primary.svg
  Evernote Clone/img/repackaging-video@2x.png
  Evernote Clone/img/right-arrow.png
  Evernote Clone/img/sec-41.png
  Evernote Clone/img/sec-43.png
  Evernote Clone/img/sec42.png
  Evernote Clone/img/sec44.png
  Evernote Clone/img/task_hero_image@2x__en.png
  Evernote Clone/img/task_icon.svg
  Evernote Clone/img/web-clipping.svg
  Evernote Clone/index.html
  Evernote Clone/style.css
Labels: Level2, GSSoC22

#558 Razer Clone
  Razer clone/README.md
  Razer clone/index.html
  Razer clone/style.css
Labels: GSSoC22, Level3

#556 Twitter-UI-clone added
  .vscode/settings.json
  Twitter-UI-Clone/css/blocks/brand.css
  Twitter-UI-Clone/css/blocks/layout.css
  Twitter-UI-Clone/css/blocks/sidebar-menu.css
  Twitter-UI-Clone/css/blocks/trends-for-you.css
  Twitter-UI-Clone/css/blocks/tweet.css
  Twitter-UI-Clone/css/blocks/who-to-follow.css
  Twitter-UI-Clone/css/global.css
  Twitter-UI-Clone/images/magic.png
  Twitter-UI-Clone/images/post-image-1.jpg
  Twitter-UI-Clone/images/profile-image-1.png
  Twitter-UI-Clone/images/profile-image-2.png
  Twitter-UI-Clone/images/profile-image-3.png
  Twitter-UI-Clone/images/profile-image-4.png
  Twitter-UI-Clone/images/shield.png
  Twitter-UI-Clone/index.html
  Twitter-UI-Clone/svg/explore.svg
  Twitter-UI-Clone/svg/home.svg
  Twitter-UI-Clone/svg/messages.svg
  Twitter-UI-Clone/svg/more.svg
  Twitter-UI-Clone/svg/notifications.svg
  Twitter-UI-Clone/svg/profile.svg
  Twitter-UI-Clone/svg/twitter.svg
Labels: Level2, GSSoC22

#566 Fixes 559
  Medium UI Clone/css/bootstrap.min.css
  Medium UI Clone/css/bootstrap.min.css.map
  Medium UI Clone/css/medium.css
  Medium UI Clone/img/world.png
  Medium UI Clone/index.html
Labels: Level2, GSSoC22

#571 Paypal UI Clone
  PayPal UI/README.md
  PayPal UI/index.html
  PayPal UI/script.js
  PayPal UI/style.css
Labels: GSSoC22

#572 added amazon clone
  amazon/.firebase/hosting.YnVpbGQ.cache
  amazon/.firebaserc
  amazon/.gitignore
  amazon/README.md
  amazon/firebase.json
  amazon/functions/.eslintrc.js
  amazon/functions/.gitignore
  amazon/functions/index.js
  amazon/functions/package-lock.json
  amazon/functions/package.json
  amazon/functions/ui-debug.log
  amazon/package-lock.json
  amazon/package.json
  amazon/public/favicon.ico
  amazon/public/index.html
  amazon/public/logo192.png
  amazon/public/logo512.png
  amazon/public/manifest.json
  amazon/public/robots.txt
  amazon/src/App.css
  amazon/src/App.js
  amazon/src/Checkout.css
  amazon/src/Checkout.js
  amazon/src/CheckoutProduct.css
  amazon/src/CheckoutProduct.js
  amazon/src/Header.css
  amazon/src/Header.js
  amazon/src/Home.css
  amazon/src/Home.js
  amazon/src/Login.css
  amazon/src/Login.js
  amazon/src/Order.css
  amazon/src/Order.js
  amazon/src/Orders.css
  amazon/src/Orders.js
  amazon/src/Payment.css
  amazon/src/Payment.js
  amazon/src/Product.css
  amazon/src/Product.js
  amazon/src/StateProvider.js
  amazon/src/Subtotal.css
  amazon/src/Subtotal.js
  amazon/src/axios.js
  amazon/src/firebase.js
  amazon/src/img/logo_amazon.jpg
  amazon/src/index.css
  amazon/src/index.js
  amazon/src/reducer.js
  amazon/src/reportWebVitals.js
  amazon/src/setupTests.js
  amazon/ui-debug.log
Labels: Level1, GSSoC22

#576 added mercedes Clone
  Mercedes Clone/README.md
  Mercedes Clone/black1.jpg
  Mercedes Clone/css/master.css
  Mercedes Clone/design-bg.webp
  Mercedes Clone/design-im.jpg
  Mercedes Clone/design-im1.jfif
  Mercedes Clone/index.html
  Mercedes Clone/landing.jpg
Labels: Level2, GSSoC22

#568 Added Trello Clone
  Trello Clone/img/Trello_logo.svg.png
  Trello Clone/img/atlassian-logo-gray-small.svg
  Trello Clone/img/atlassian-logo-white-small.svg
  Trello Clone/img/automation.png
  Trello Clone/img/board.png
  Trello Clone/img/card-back.svg
  Trello Clone/img/caret-right.svg
  Trello Clone/img/coinbase.png
  Trello Clone/img/compass.svg
  Trello Clone/img/ebay.svg
  Trello Clone/img/google.png
  Trello Clone/img/grand.png
  Trello Clone/img/hero.png
  Trello Clone/img/john.png
  Trello Clone/img/left-arrow.png
  Trello Clone/img/left-quote.png
  Trello Clone/img/power-ups.png
  Trello Clone/img/right-arrows.png
  Trello Clone/img/tag.svg
  Trello Clone/img/view.svg
  Trello Clone/img/visa.png
  Trello Clone/img/zoom.png
  Trello Clone/index.html
  Trello Clone/style.css
Labels: Level2, GSSoC22

#569 Add a Udemy Clone
  Udemy Clone/.gitignore
  Udemy Clone/README.md
  Udemy Clone/package.json
  Udemy Clone/public/awscourse.jpeg
  Udemy Clone/public/business.jpeg
  Udemy Clone/public/design.jpeg
  Udemy Clone/public/development.jpeg
  Udemy Clone/public/index.html
  Udemy Clone/public/manifest.json
  Udemy Clone/public/marketing.jpeg
  Udemy Clone/public/music.jpeg
  Udemy Clone/public/personal.jpeg
  Udemy Clone/public/photography.jpeg
  Udemy Clone/public/python-yu.jpeg
  Udemy Clone/public/robots.txt
  Udemy Clone/public/software.jpeg
  Udemy Clone/public/udebusiness.png
  Udemy Clone/public/udemy-business-logo.png
  Udemy Clone/public/udemy.png
  Udemy Clone/public/udemybusiness.jpeg
  Udemy Clone/public/udemylogo.png
  Udemy Clone/src/App.css
  Udemy Clone/src/App.js
  Udemy Clone/src/App.test.js
  Udemy Clone/src/components/Header.js
  Udemy Clone/src/components/HomeContent.js
  Udemy Clone/src/components/HomeFooter.js
  Udemy Clone/src/components/footer/footer.css
  Udemy Clone/src/components/footer/footer.js
  Udemy Clone/src/components/header/headerPopup.css
  Udemy Clone/src/components/header/headerPopup.js
  Udemy Clone/src/components/header/headerPrimary.css
  Udemy Clone/src/components/header/headerPrimary.js
  Udemy Clone/src/components/homeContent/adImage.css
  Udemy Clone/src/components/homeContent/adImage.js
  Udemy Clone/src/components/homeContent/becomeInstructor.css
  Udemy Clone/src/components/homeContent/becomeInstructor.js
  Udemy Clone/src/components/homeContent/featureDiv/featureCard.css
  Udemy Clone/src/components/homeContent/featureDiv/featureCard.js
  Udemy Clone/src/components/homeContent/fillerDiv.css
  Udemy Clone/src/components/homeContent/fillerDiv.js
  Udemy Clone/src/components/homeContent/recommendations/recommendations.css
  Udemy Clone/src/components/homeContent/recommendations/recommendations.js
  Udemy Clone/src/components/homeContent/recommendations/recommendedVideos.css
  Udemy Clone/src/components/homeContent/recommendations/recommendedVideos.js
  Udemy Clone/src/components/homeContent/recommendations/videoCard.css
  Udemy Clone/src/components/homeContent/recommendations/videoCard.js
  Udemy Clone/src/components/homeContent/topCategories/categoryCard.css
  Udemy Clone/src/components/homeContent/topCategories/categoryCard.js
  Udemy Clone/src/components/homeContent/topCategories/topCategories.css
  Udemy Clone/src/components/homeContent/topCategories/topCategories.js
  Udemy Clone/src/components/homeContent/trustedCompanies.css
  Udemy Clone/src/components/homeContent/trustedCompanies.js
  Udemy Clone/src/components/homeContent/udemyForBusiness.css
  Udemy Clone/src/components/homeContent/udemyForBusiness.js
  Udemy Clone/src/index.css
  Udemy Clone/src/index.js
Labels: Level2, GSSoC22

#589 Sololearn Clone
  Sololearn Clone/assets/1.png
  Sololearn Clone/assets/10.png
  Sololearn Clone/assets/11.png
  Sololearn Clone/assets/12.png
  Sololearn Clone/assets/13.png
  Sololearn Clone/assets/14.png
  Sololearn Clone/assets/15.png
  Sololearn Clone/assets/16.png
  Sololearn Clone/assets/17.png
  Sololearn Clone/assets/18.png
  Sololearn Clone/assets/19.png
  Sololearn Clone/assets/2.png
  Sololearn Clone/assets/20.png
  Sololearn Clone/assets/21.png
  Sololearn Clone/assets/22.png
  Sololearn Clone/assets/23.png
  Sololearn Clone/assets/24.png
  Sololearn Clone/assets/25.png
  Sololearn Clone/assets/3.png
  Sololearn Clone/assets/4.png
  Sololearn Clone/assets/5.png
  Sololearn Clone/assets/6.png
  Sololearn Clone/assets/7.png
  Sololearn Clone/assets/8.png
  Sololearn Clone/assets/9.png
  Sololearn Clone/assets/favicon.svg
  Sololearn Clone/assets/hero.png
  Sololearn Clone/index.html
  Sololearn Clone/script.js
  Sololearn Clone/style.css
Labels: Level2, GSSoC22

#585 Hash node Clone
  Hashnode Clone/images/analytics.svg
  Hashnode Clone/images/bell.svg
  Hashnode Clone/images/bookmarks.svg
  Hashnode Clone/images/brand-icon.pdf
  Hashnode Clone/images/brand-icon.png
  Hashnode Clone/images/caret-down.svg
  Hashnode Clone/images/chat-illustration.png
  Hashnode Clone/images/custom-domain.svg
  Hashnode Clone/images/custom.svg
  Hashnode Clone/images/dark-toggle.svg
  Hashnode Clone/images/data.svg
  Hashnode Clone/images/drafts.svg
  Hashnode Clone/images/explore.svg
  Hashnode Clone/images/feed-illustration.png
  Hashnode Clone/images/feed.svg
  Hashnode Clone/images/github.svg
  Hashnode Clone/images/guillermo-rauch.jpeg
  Hashnode Clone/images/https_ssl.svg
  Hashnode Clone/images/illustration-five.png
  Hashnode Clone/images/illustration-four.png
  Hashnode Clone/images/illustration-one.png
  Hashnode Clone/images/illustration-three.png
  Hashnode Clone/images/illustration-two.png
  Hashnode Clone/images/james-q-quick.jpg
  Hashnode Clone/images/light-toggle.svg
  Hashnode Clone/images/markdown.svg
  Hashnode Clone/images/newsletter.svg
  Hashnode Clone/images/pencil.svg
  Hashnode Clone/images/quincy-larson.jpeg
  Hashnode Clone/images/search.svg
  Hashnode Clone/images/series.svg
  Hashnode Clone/images/simon-holdorf.jpeg
  Hashnode Clone/images/ssl.svg
  Hashnode Clone/images/superfast.svg
  Hashnode Clone/images/tags.svg
  Hashnode Clone/images/user-profile.png
  Hashnode Clone/images/web-illustration.png
  Hashnode Clone/index.html
  Hashnode Clone/main.css
  Hashnode Clone/script.js
Labels: Level2, GSSoC22

#584 Added WorkFlowy Clone
  WorkFlowy/img/atlassian.svg
  WorkFlowy/img/hatching.svg
  WorkFlowy/img/logo.svg
  WorkFlowy/img/newyork.svg
  WorkFlowy/img/slack.svg
  WorkFlowy/img/twitter.svg
  WorkFlowy/img/workflowy.svg
  WorkFlowy/index.html
  WorkFlowy/style.css
Labels: Level1, GSSoC22

#594 added Coursera Responsive Code
  Coursera Clone/css/style.css
  Coursera Clone/images/bn1.jpg
  Coursera Clone/images/bn13.jpg
  Coursera Clone/images/bn6.jpg
  Coursera Clone/images/coursera.png
  Coursera Clone/images/qwe.jpg
  Coursera Clone/index.html
  Coursera Clone/readme.md
Labels: Level2, GSSoC22

#597 TinDog website added
  TinDog/css/.DS_Store
  TinDog/css/styles.css
  TinDog/images/.DS_Store
  TinDog/images/Dog.png
  TinDog/images/TechCrunch.png
  TinDog/images/bizinsider.png
  TinDog/images/dog-img.jpg
  TinDog/images/favicon.ico
  TinDog/images/iphone6.png
  TinDog/images/lady-img.jpg
  TinDog/images/mashable.png
  TinDog/images/tnw.png
  TinDog/index.html
Labels: Level2, GSSoC22

#601 GSSoC Clone
  GirlScript/README.md
  GirlScript/Screenshot (360).png
  GirlScript/Screenshot (361).png
  GirlScript/Screenshot (362).png
  GirlScript/Screenshot (363).png
  GirlScript/Screenshot (364).png
  GirlScript/Screenshot (365).png
  GirlScript/Screenshot (366).png
  GirlScript/index.html
  GirlScript/script.js
  GirlScript/style.css
Labels: GSSoC22, Level3

#598 Added Patatap clone
  Patatap Clone/README.md
  Patatap Clone/circles.css
  Patatap Clone/data.js
  Patatap Clone/index.html
  Patatap Clone/paper-full.js
  Patatap Clone/sounds/README.md
  Patatap Clone/sounds/bubbles.mp3
  Patatap Clone/sounds/clay.mp3
  Patatap Clone/sounds/confetti.mp3
  Patatap Clone/sounds/corona.mp3
  Patatap Clone/sounds/dotted-spiral.mp3
  Patatap Clone/sounds/flash-1.mp3
  Patatap Clone/sounds/flash-2.mp3
  Patatap Clone/sounds/flash-3.mp3
  Patatap Clone/sounds/glimmer.mp3
  Patatap Clone/sounds/moon.mp3
  Patatap Clone/sounds/pinwheel.mp3
  Patatap Clone/sounds/piston-1.mp3
  Patatap Clone/sounds/piston-2.mp3
  Patatap Clone/sounds/piston-3.mp3
  Patatap Clone/sounds/prism-1.mp3
  Patatap Clone/sounds/prism-2.mp3
  Patatap Clone/sounds/prism-3.mp3
  Patatap Clone/sounds/splits.mp3
  Patatap Clone/sounds/squiggle.mp3
  Patatap Clone/sounds/strike.mp3
  Patatap Clone/sounds/suspension.mp3
  Patatap Clone/sounds/timer.mp3
  Patatap Clone/sounds/ufo.mp3
  Patatap Clone/sounds/veil.mp3
  Patatap Clone/sounds/wipe.mp3
  Patatap Clone/sounds/zig-zag.mp3
Labels: GSSoC22, Level3

#607 Added urban Company Clone
  Urban Company Clone/css/footer.css
  Urban Company Clone/css/header.css
  Urban Company Clone/css/section-1.css
  Urban Company Clone/css/section-2.css
  Urban Company Clone/img/app.png
  Urban Company Clone/img/checkout.webp
  Urban Company Clone/img/flag.jpg
  Urban Company Clone/img/google.png
  Urban Company Clone/img/logo.png
  Urban Company Clone/img/next.png
  Urban Company Clone/img/salon.webp
  Urban Company Clone/img/sec-1.webp
  Urban Company Clone/img/sec-2-1-1.webp
  Urban Company Clone/img/sec-2-1-2.webp
  Urban Company Clone/img/sec-2-1-3.webp
  Urban Company Clone/img/sec-2-1-right.webp
  Urban Company Clone/img/social/facebook.png
  Urban Company Clone/img/social/instagram.png
  Urban Company Clone/img/social/linkedin-logo.png
  Urban Company Clone/img/social/pinterest.png
  Urban Company Clone/img/social/twitter.png
  Urban Company Clone/img/social/youtube.png
  Urban Company Clone/index.html
Labels: Level2, GSSoC22

#605 Skeleton effect
  skeleton-react/.gitignore
  skeleton-react/README.md
  skeleton-react/package.json
  skeleton-react/public/favicon.ico
  skeleton-react/public/index.html
  skeleton-react/public/logo192.png
  skeleton-react/public/logo512.png
  skeleton-react/public/manifest.json
  skeleton-react/public/robots.txt
  skeleton-react/src/App.js
  skeleton-react/src/comp/Articles.js
  skeleton-react/src/comp/User.js
  skeleton-react/src/index.css
  skeleton-react/src/index.js
  skeleton-react/src/reportWebVitals.js
  skeleton-react/src/skeletons/Shimmer.js
  skeleton-react/src/skeletons/Skeleton.css
  skeleton-react/src/skeletons/SkeletonArticle.js
  skeleton-react/src/skeletons/SkeletonElement.js
  skeleton-react/src/skeletons/SkeletonProfile.js
Labels: Level1, GSSoC22

#608 Added Responsive Honda Clone
  Honda Website Clone/css/style.css
  Honda Website Clone/images/269715025_286442796874460_323404473126266481_n.jpg
  Honda Website Clone/images/acura-logo.png
  Honda Website Clone/images/carrousel-img.webp
  Honda Website Clone/images/global-logo.svg
  Honda Website Clone/images/hinh1.jpg
  Honda Website Clone/images/hinh10.webp
  Honda Website Clone/images/hinh11.jpg
  Honda Website Clone/images/hinh12.jpg
  Honda Website Clone/images/hinh13.webp
  Honda Website Clone/images/hinh14.jpg
  Honda Website Clone/images/hinh15.jpg
  Honda Website Clone/images/hinh17.jpg
  Honda Website Clone/images/hinh18.jpg
  Honda Website Clone/images/hinh19.jpg
  Honda Website Clone/images/hinh2.jpg
  Honda Website Clone/images/hinh20.jpg
  Honda Website Clone/images/hinh21.jpg
  Honda Website Clone/images/hinh3.jpg
  Honda Website Clone/images/hinh4.jpg
  Honda Website Clone/images/hinh5.jpg
  Honda Website Clone/images/hinh6.jpg
  Honda Website Clone/images/hinh7.webp
  Honda Website Clone/images/hinh8.webp
  Honda Website Clone/images/hinh9.jpg
  Honda Website Clone/images/podcast-logo.webp
  Honda Website Clone/images/readicon.svg
  Honda Website Clone/index.html
  Honda Website Clone/readme.md
Labels: GSSoC22, Level3

#654 Added Samsung Clone
  Samsung Clone/index.html
  Samsung Clone/style.css
Labels: Level2, GSSoC22

#648 Chat app
  chat_app/.gitignore
  chat_app/README.md
  chat_app/public/favicon.ico
  chat_app/public/index.html
  chat_app/public/logo192.png
  chat_app/public/logo512.png
  chat_app/public/manifest.json
  chat_app/public/robots.txt
  chat_app/src/App.css
  chat_app/src/App.js
  chat_app/src/components/ChatFeed.jsx
  chat_app/src/components/LoginForm.jsx
  chat_app/src/components/MessageForm.jsx
  chat_app/src/components/MyMessage.jsx
  chat_app/src/components/TheirMessage.jsx
  chat_app/src/index.js
Labels: GSSoC22, Level3

#661 Food menu
  food_menu/.gitignore
  food_menu/README.md
  food_menu/public/favicon.ico
  food_menu/public/index.html
  food_menu/public/logo192.png
  food_menu/public/logo512.png
  food_menu/public/manifest.json
  food_menu/public/robots.txt
  food_menu/src/App.css
  food_menu/src/App.js
  food_menu/src/components/Alert.js
  food_menu/src/components/Recipe.js
  food_menu/src/components/RecipeDetails.js
  food_menu/src/index.js
Labels: GSSoC22

#660 Google Meet
  Google Meet/index.html
  Google Meet/style.css
Labels: Level2, GSSoC22

#663 Google Duo
  GoogleDuo/img/bg.svg
  GoogleDuo/img/duo.svg
  GoogleDuo/img/icon.png
  GoogleDuo/img/msg.png
  GoogleDuo/index.html
  GoogleDuo/style.css
Labels: Level1, GSSoC22

#668 nike shoes shop
  nike_shoes_shop/images/nike.png
  nike_shoes_shop/images/shoe1.png
  nike_shoes_shop/images/shoe2.png
  nike_shoes_shop/index.html
  nike_shoes_shop/script.js
  nike_shoes_shop/style.css
Labels: Level2, GSSoC22

#671 Premium Wine yard shop
  wine_yard_shop/images/arrow.png
  wine_yard_shop/images/bag.png
  wine_yard_shop/images/footer-img.png
  wine_yard_shop/images/frame.png
  wine_yard_shop/images/grapes.png
  wine_yard_shop/images/logo.png
  wine_yard_shop/images/section-1-bg.jpg
  wine_yard_shop/images/section-2-bg.jpg
  wine_yard_shop/images/section-3-bg.jpg
  wine_yard_shop/images/section-4-bg.jpg
  wine_yard_shop/images/section-5-bg.jpg
  wine_yard_shop/images/wine-bottle.png
  wine_yard_shop/index.html
  wine_yard_shop/script.js
  wine_yard_shop/style.css
Labels: Level2, GSSoC22

#674 Tesla clone ReactJS
  Tesla Clone ReactJS/package.json
  Tesla Clone ReactJS/public/favicon.ico
  Tesla Clone ReactJS/public/images/accessories.jpg
  Tesla Clone ReactJS/public/images/audio.jpg
  Tesla Clone ReactJS/public/images/connected.jpg
  Tesla Clone ReactJS/public/images/down-arrow.png
  Tesla Clone ReactJS/public/images/game.jpg
  Tesla Clone ReactJS/public/images/logo.svg
  Tesla Clone ReactJS/public/images/model-3.jpg
  Tesla Clone ReactJS/public/images/model-s.jpg
  Tesla Clone ReactJS/public/images/model-x.jpg
  Tesla Clone ReactJS/public/images/model-y.jpg
  Tesla Clone ReactJS/public/images/new-interior.jpg
  Tesla Clone ReactJS/public/images/solar-panel.jpg
  Tesla Clone ReactJS/public/images/solar-roof.jpg
  Tesla Clone ReactJS/public/index.html
  Tesla Clone ReactJS/public/manifest.json
  Tesla Clone ReactJS/public/robots.txt
  Tesla Clone ReactJS/src/App.css
  Tesla Clone ReactJS/src/App.js
  Tesla Clone ReactJS/src/App.test.js
  Tesla Clone ReactJS/src/app/store.js
  Tesla Clone ReactJS/src/components/Header.js
  Tesla Clone ReactJS/src/components/Home.js
  Tesla Clone ReactJS/src/components/Section.js
  Tesla Clone ReactJS/src/features/car/carSlice.js
  Tesla Clone ReactJS/src/index.css
  Tesla Clone ReactJS/src/index.js
  Tesla Clone ReactJS/src/logo.svg
  Tesla Clone ReactJS/src/serviceWorker.js
  Tesla Clone ReactJS/src/setupTests.js
Labels: Level2, GSSoC22

#675 Loruki clone
  Loruki Clone/.gitignore
  Loruki Clone/Public/404.html
  Loruki Clone/Public/css/style.css
  Loruki Clone/Public/css/utalities.css
  Loruki Clone/Public/docs.html
  Loruki Clone/Public/features.html
  Loruki Clone/Public/images/cli.png
  Loruki Clone/Public/images/cloud.png
  Loruki Clone/Public/images/docs.png
  Loruki Clone/Public/images/favicon.png
  Loruki Clone/Public/images/logos/clojure.png
  Loruki Clone/Public/images/logos/csharp.png
  Loruki Clone/Public/images/logos/go.png
  Loruki Clone/Public/images/logos/node.png
  Loruki Clone/Public/images/logos/php.png
  Loruki Clone/Public/images/logos/python.png
  Loruki Clone/Public/images/logos/ruby.png
  Loruki Clone/Public/images/logos/scala.png
  Loruki Clone/Public/images/npm.png
  Loruki Clone/Public/images/server.png
  Loruki Clone/Public/images/server2.png
  Loruki Clone/Public/index.html
  Loruki Clone/css/style.css
  Loruki Clone/css/utalities.css
  Loruki Clone/docs.html
  Loruki Clone/features.html
  Loruki Clone/images/cli.png
  Loruki Clone/images/cloud.png
  Loruki Clone/images/docs.png
  Loruki Clone/images/favicon.png
  Loruki Clone/images/logos/clojure.png
  Loruki Clone/images/logos/csharp.png
  Loruki Clone/images/logos/go.png
  Loruki Clone/images/logos/node.png
  Loruki Clone/images/logos/php.png
  Loruki Clone/images/logos/python.png
  Loruki Clone/images/logos/ruby.png
  Loruki Clone/images/logos/scala.png
  Loruki Clone/images/npm.png
  Loruki Clone/images/server.png
  Loruki Clone/images/server2.png
  Loruki Clone/index.html
Labels: GSSoC22

#677 design and architecture site
  design_and_architecture_site/images/bg.jpg
  design_and_architecture_site/images/contact-bg.jpg
  design_and_architecture_site/images/house.png
  design_and_architecture_site/images/person-1.jpg
  design_and_architecture_site/images/person-2.jpg
  design_and_architecture_site/images/person-3.jpg
  design_and_architecture_site/index.html
  design_and_architecture_site/script.js
  design_and_architecture_site/style.css
  design_and_architecture_site/tilt.js
Labels: Level2, GSSoC22

#678 Added Apna Clone
  Apna Clone/img/Employer.png
  Apna Clone/img/MNCs.png
  Apna Clone/img/apna.png
  Apna Clone/img/news.png
  Apna Clone/img/searchjob.png
  Apna Clone/img/sec-1-left.webp
  Apna Clone/img/sec-1-right.webp
  Apna Clone/index.html
  Apna Clone/style.css
Labels: Level2, GSSoC22

#679 Authentication API using NodeJS
  Auth_API/.gitignore
  Auth_API/Procfile
  Auth_API/README.md
  Auth_API/app.js
  Auth_API/middleware/auth.js
  Auth_API/models/User.js
  Auth_API/package.json
  Auth_API/routes/home.js
  Auth_API/routes/otp.js
  Auth_API/routes/user.js
Labels: GSSoC22, Level3

#656 Stack Overflow
  Stackoverflow UI'/index.html
  Stackoverflow UI'/main.css
  Stackoverflow UI'/main.js
Labels: GSSoC22

#627 Coca Cola
  Coca Cola Clone/README.md
  Coca Cola Clone/icon.png
  Coca Cola Clone/img/close.png
  Coca Cola Clone/img/cocacola1.png
  Coca Cola Clone/img/cocacola2.png
  Coca Cola Clone/img/cocacola3.png
  Coca Cola Clone/img/cocacola4.png
  Coca Cola Clone/img/cocacola5.png
  Coca Cola Clone/img/cocacola6.png
  Coca Cola Clone/img/logo.png
  Coca Cola Clone/img/menu.png
  Coca Cola Clone/index.html
  Coca Cola Clone/preview.jpg
  Coca Cola Clone/preview1.jpg
  Coca Cola Clone/preview2.jpg
  Coca Cola Clone/style.css
Labels: Level2, GSSoC22

#634 Vimeo
  Vimeo/index.html
  Vimeo/script.js
  Vimeo/style.css
Labels: Level2, GSSoC22

#630 Pepsi
  Pepsi Clone/index.html
  Pepsi Clone/readme.md
  Pepsi Clone/style.css
Labels: Level2, GSSoC22
